### ISSUE TITLE
Log added and removed keys

### ISSUE THREAD

**Issue by nickasd** [i18next/i18next-parser#101]
- Is this a bug or a feature request? Feature request
- What version are you running (`0.x` or `1.x`)? 1.0.0-beta14
- Which runner (cli, gulp...)? gulp

It would be nice if the parser would output a list of keys that have been added and removed. This way one can immediately see if new additions were correctly parsed and translate them immediately without first having to compare the output json file with the old version.

Thanks for this great program, it really helps me a lot! I'm happy to make a pull request if desired.

**Comment by karellm** [comment]
Is there a reason you cannot look at the git diff?

**Comment by nickasd** [comment]
I knew this was coming ;-) It's not meant as a replacement for the git diff, rather as a quick way of ensuring that everything went smooth. I guess once you know that everything is set up correctly you will only make use of the git diff, but for new users it would be a nice feedback to know if anything is going on.

Scenario: as I was trying to figure out how this whole thing works, I hadn't set up everything correctly and I had to run the program several times and inspect the output json file every time to check if something happened. Also as I was debugging #100 and editing the Handlebars lexer's source code I had to inspect the output after each change to test if the second key on the same line still hadn't got parsed. Instead it would have been nice to have at least a line telling me how many (new) keys were parsed.

**Comment by karellm** [comment]
If you feel like making a PR I will review it. I would require this to be an option though.

**Comment by nickasd** [comment]
I was working on this today and wondering if in `mergeHashes()` it's really necessary to add removed keys to both the current and old catalogs when the option `keepRemoved` is set. I think that this is not expected behaviour, but the reason why I'm asking is that this kind of messes up the counts of added/merged/removed keys. What do you think?

**Comment by karellm** [comment]
I think it's ok have it only part of the current catalog. The point of the `_old` catalog is really to avoid loosing data.

**Comment by nickasd** [comment]
Ok great. I also have another question. Is there a specific reason why in `populateHash` you only restore an old key if the current value is the empty string? While testing I noticed that if I remove a key with a default value in the html, run the parser, restore the key with the default value in the html, and run the parser again, the key is kept in the old catalog and never restored. I would have expected it to be restored from the old catalog when I restored it in the html.

**Comment by karellm** [comment]
@nickasd I think your assumption is correct. If you want to make a separate PR with test addressing this issue, I will merge it. Thanks!

**Comment by karellm** [comment]
@nickasd I merged #105. In the future, please create a new ticket for new issues. It was not really related with #101. On that note, should we close this or do you plan on making a PR for it? Thanks!

**Comment by nickasd** [comment]
Thanks. Ok, I will. A PR for #101 will follow shortly.

**Comment by karellm** [comment]
Fixed in `1.0.0-beta21`
