### ISSUE TITLE
Version Discrepancy: NPM 9.0.1 vs GitHub 8.0.0

### ISSUE THREAD

**Issue by cedricalfonsi** [i18next/i18next-parser#1044]
Hey guys, 

I have observed a discrepancy between the latest version listed on the npm repository (9.0.1) and the version available on GitHub (8.0.0). Could you please confirm if 9.0.1 is indeed the most current version of the library?

**Comment by karellm** [comment]
You can use `9.0.1` which is the latest. I will release it on github shortly to avoid confusion
