### ISSUE TITLE
Add support for i18next v24

### ISSUE THREAD

**Issue by lazka** [i18next/i18next-parser#1090]
## 🚀 Feature Proposal

v24 was released some days ago: https://github.com/i18next/i18next/releases/tag/v24.0.0

Migration guide: https://www.i18next.com/misc/migration-guide#v23.x.x-to-v24.0.0

The changes seem limited, so I hope it's not too hard to update. Maybe it might even be possible to support both versions in case the dropping of old browser support is an issue? It's not an issue for me at least.

## Motivation

I'd like to update to v24, but i18next-parser is blocking the update.

## Example

npm update :)

**Comment by lazka** [comment]
I've created a PR #1093

**Comment by karellm** [comment]
Deployed as `9.1.0`
