### ISSUE TITLE
Appending, not replacing the contents of the destination file

### ISSUE THREAD

**Issue by HamidAghdaee** [i18next/i18next-parser#114]
- Is this a bug or a feature request?
Feature Request.

## What I'm trying to do?

*Replace this with a description of what you are trying to do*

Hi there, 

Thank you for this wonderful library. 

The ideal scenario for me would be:

1. The developer inserts call to `i18next.t` in their code with a key `ns:key`, i18next-parser job is run. 
2. If the job finds the `key` with a non null value in the file `ns`, then it's left alone. If not, its inserted into the file with the value `null`. It is the job of the developer to then provide a value for this key into the translation file. 
3. If the job find any keys not used in source code they're removed from the resource file.

Essentially, I would like it to leave alone any keys for which there are values in the translation file already, add any that are new in source code and remove any that are in translation file and not in source code. 

What's the best way to achieve this with your tool?

Thank you.

-Hamid

**Comment by karellm** [comment]
This should be the default behaviour, if not it's a bug, not a feature request. Can you provide some reproducible steps (follow the template for filling the issue)? If you feel confortable writing a failing test case that's even better.

**Comment by HamidAghdaee** [comment]
@karellm You're absolutely right. My fault. closing this ticket. Thanks for your help.
