### ISSUE TITLE
More info in case config can't be loaded

### ISSUE THREAD

**Issue by cgomezmendez** [i18next/i18next-parser#115]
https://github.com/i18next/i18next-parser/blob/ae18bfbeb822bb818fff9a6b85d536117f045acf/bin/cli.js#L32

Spent a lot of time debugging cause it said that config file didn't exist, tried even with linux (I'm using windows) in case it was an OS path problem, well the thing is that the config filed I copied I think it was from some issue here or something had this:
  "lineEnding": auto
instead of this:
  "lineEnding": 'auto',
and it was throwing auto is not defined

But to get there I had to run a node instance and execute the code in this line to be able to debug it.

**Comment by karellm** [comment]
Thanks, I've updated the README!
