### ISSUE TITLE
Add static properties acorn plugin

### ISSUE THREAD

**Issue by tstirrat15** [i18next/i18next-parser#121]
# Proposal
My project uses static property syntax, which Acorn doesn't parse natively, which means this package is throwing errors. I'd like to add this to the project.

## One approach
It'd be pretty easy to include this in the same way that the other plugins are already included, which would fix my issue right now.

## Another approach
Provide a way to inject plugins through the configuration file. A proposed approach for the `acorn` configuration block:
```javascript
var injectAcornStaticClassPropertyInitializer = require('acorn-static-class-property-initializer/inject');
...
acorn: {
  injectors: [injectAcornStaticClassPropertyInitializer],
  plugins: {
    staticClassPropertyInitializer: true,
  },
}
...
```
This approach would have the benefit of being forward compatible (i.e. there wouldn't be additional work required to add additional plugins in the future) and also allow you to make the acorn plugins `optionalDependencies` of the project.

Thoughts?

**Comment by karellm** [comment]
On the one hand I like the idea to reduce dependencies of the project. On the other hand I like the simplicity of a boolean config.

I think my vote would go to the `injectors` though. As you said it is future proof and lower the number of dependencies for most people. Would you be open to make a PR?

**Comment by tstirrat15** [comment]
Sure thing. I'll get around to this next week.
