### ISSUE TITLE
Multiple failures on JSX/TSX with 1.0.0-beta28

### ISSUE THREAD

**Issue by tkrotoff** [i18next/i18next-parser#129]
Configuration:
```JS
module.exports = {
  locales: ['fr'],
  output: 'locales/$LOCALE/$NAMESPACE.json'
};
```
```
i18next '**/*.{ts,tsx}' --config i18next-parser.config.js
```

- First bug:

```JSX
<label>
  {t('Language:')}{' '}
  {/* ... */}
</label>
```

i18next-parser does not like line `{t('Language:')}{' '}` and generates a new empty file `locales/fr/Language.json` instead of adding `"Language:": "Langue :"` to `locales/fr/translation.json`

See https://github.com/tkrotoff/react-form-with-constraints/blob/v0.9.3/examples/SignUp/App.tsx#L207

- Second bug:

```JSX
<div>{t('Hmm, you seem a bit young...')}</div>
```
i18next-parser generates `locales/fr/translation.json`:
```
"Hmm, you seem a bit young": {
  "": ""
}
```
instead of:
```
"Hmm, you seem a bit young...": "Humm, vous êtes trop jeune..."
```

<br>
<br>

Diff between the expected output and v1.0.0-beta28:

![screen shot 2018-09-15 at 23 44 14](https://user-images.githubusercontent.com/643434/45590788-4d8e8a00-b941-11e8-9778-a2132ae22d55.png)

Example is here: https://github.com/tkrotoff/react-form-with-constraints/blob/v0.9.3/examples/SignUp (I've replaced React fragments (`<> ... </>`) with `<React.Fragment>` to make it work, see #128)
Example available online: https://codesandbox.io/s/62qwozvm0k

**Comment by karellm** [comment]
These shouldn't have been introduced with beta28. These are features, not bugs.

`.` and `:` are respectively the key and namespace separators. Please read about them in the REAMDE if you want to use plain english keys.

**Comment by tkrotoff** [comment]
Oh sorry, forgot to report `--namespace-separator '__NS' --key-separator '__KS'` from the command line to the configuration file:

```
module.exports = {
  locales: ['fr'],
  output: 'locales/$LOCALE/$NAMESPACE.json',
  namespaceSeparator: '__NS',
  keySeparator: '__KS'
};
```

It works perfectly!! (except for React fragments)
