### ISSUE TITLE
Generate plural keys

### ISSUE THREAD

**Issue by jsomsanith** [i18next/i18next-parser#138]
- Is this a bug or a feature request?
Feature request

- What version are you running (`0.x` or `1.x`)? 
0.x

- Which runner (cli, gulp...)?
cli

## What I'm trying to do?

I want to propose a solution to #19. I'm having the same issue. I want to set only 1 key in my code. But it relies on a `count` value, and I want the parser to generate those keys.
- `_plural`
- '_x' (x from 0 to 5) as those are rules configured for each languages.

## How am I doing it?

Let's introduce a flag that will do that under a defined convention.
Let's say
- cli option : `--plural` to activate this behavior
- the parser detects if an option is named `count`. In this case, it adds the plural 6 keys.

The command I'm running:

```shell
i18next ./src -r --fileFilter "*.js" --default-values --plural 
```

## What is the result?

*Code*
```javascript
<sup
	className={`${theme.badge} badge`}
	aria-label={t('TC_OBJECT_VIEWER_NB_CHILDREN', {
		defaultValue: 'Contains {{count}} children',
		count: info.length,
	})}
>
	info.length
</sup>
```

*Output*
```json
{
	"TC_OBJECT_VIEWER_NB_CHILDREN": "Contains {{count}} children",
	"TC_OBJECT_VIEWER_NB_CHILDREN_plural": "Contains {{count}} children",
	"TC_OBJECT_VIEWER_NB_CHILDREN_0": "Contains {{count}} children",
	"TC_OBJECT_VIEWER_NB_CHILDREN_1": "Contains {{count}} children",
	"TC_OBJECT_VIEWER_NB_CHILDREN_2": "Contains {{count}} children",
	"TC_OBJECT_VIEWER_NB_CHILDREN_3": "Contains {{count}} children",
	"TC_OBJECT_VIEWER_NB_CHILDREN_4": "Contains {{count}} children",
	"TC_OBJECT_VIEWER_NB_CHILDREN_5": "Contains {{count}} children",
}
```

Then I can pass that to translation system/team with a table explaining the `_x` by language to translate.

**Comment by karellm** [comment]
I'm a bit confused by your proposal though I find the idea interesting. Do you want to detect the `count` option and when it's present, add the plural keys based on a configuration like so:

```
{
  locales: ['en', 'de'],
  output: 'locales/$LOCALE/$NAMESPACE.json',
  plural: {
    de: ["plural", 2, 3],
    en: ["plural"]
  }
}
```

and then the following code:

```js
t('key', {count: 3})
```

would create this in English:

```js
{
  key: '',
  key_plural: ''
}
```

and this in Dutch:

```js
{
  key: '',
  key_plural: '',
  key_2: '',
  key_3: ''
}
```

If so, I would be open for a PR. I think it has value.

**Comment by jsomsanith** [comment]
Hi @karellm,

I haven't thought of that details you brought.
In fact my need is that I have only english extracted file. Based on this file I can request a translation to any language. So I need all the plural keys.

I will not have the time (really) soon, to work on that, but when the time comes, I can propose a PR. For now I want to clarify the idea.

Perhaps we can have a default that outputs all the plurals, and a configuration that enables to select them.

**Comment by karellm** [comment]
There could be a simpler version of the config that works for all languages:

```
{
  plural: 3
}
```

I don't have the time either at the moment but a PR is welcome!

**Comment by jsomsanith** [comment]
The shortcut can be handy, the problem is that it's not really explicit. (Not sure it's a problem).

**Comment by jsomsanith** [comment]
For info, I'll drop this proposal because I won't have the need anymore (and no time for that). If someone wants to take it, I'm sure i18next-parser users would be find it useful.

**Comment by karellm** [comment]
Then I will close this, if anyone feels to tackle this, feel free to reopen
