### ISSUE TITLE
Why duplicate translations with context ?

### ISSUE THREAD

**Issue by sebdiem** [i18next/i18next-parser#143]
- Is this a bug or a feature request? Question
- What version are you running (`0.x` or `1.x`)? `1.x` 
- Which runner (cli, gulp...)? `cli`

## What I'm trying to do?

I am trying to extract a message with context.

## How am I doing it?

Here is my config file:

```
{
  locales: ['en', 'de'],
  output: 'locales/$LOCALE/$NAMESPACE.json'
}
```
Here is my component:

```
const Home = (props: IProps) => {
  const { t } = props;
  return (
    <Typography variant="body1">
      {t(
        "This is the homepage. Please use the left menu to navigate through the different sections of the app.",
        {context: "with context"},
      )}
    </Typography>
  );
};```

The command I'm running:

```
i18next "src/**/*.tsx" --config i18next-parser.config.js --output public/locales/\$LOCALE/\$NAMESPACE.json
```

## What was the result?

```$ cat public/locales/en/translation.json
{
  "This is the homepage. Please use the left menu to navigate through the different sections of the app.": "TODO",
  "This is the homepage. Please use the left menu to navigate through the different sections of the app._with context": "TODO"
}
```

## What was I expecting?

```$ cat public/locales/en/translation.json
{
  "This is the homepage. Please use the left menu to navigate through the different sections of the app._with context": "TODO"
}
```

The code responsible for this behaviour can be found here:
https://github.com/i18next/i18next-parser/blob/ae18bfbeb822bb818fff9a6b85d536117f045acf/src/transform.js#L187-L196

and the test:
https://github.com/i18next/i18next-parser/blob/ae18bfbeb822bb818fff9a6b85d536117f045acf/test/parser.test.js#L54-L76

I understand that this is the expected behavior but what is the reasoning behind this ? Why should I translate my message twice ?

**Comment by karellm** [comment]
I invite you to read about the `context` feature in the [i18next documentation](https://www.i18next.com/translation-function/context). If you add a context, it is supposedly that the translation should change based on that context, otherwise why would you even put a context?

**Comment by sebdiem** [comment]
> If you add a context, it is supposedly that the translation should change based on that context, otherwise why would you even put a context?

But if you use the same message with and without context, the message without context will in any case be handled separately by the parser, so I don't see why you need to add it when parsing the message with context.

**Comment by karellm** [comment]
Indeed, thanks for the pointer and it will be added in `1.0.0-beta36`
