### ISSUE TITLE
Export in yml

### ISSUE THREAD

**Issue by pinkynrg** [i18next/i18next-parser#146]
If I needed for my project's translations to be in yml format? Is there an easy way to do it that you guys can think of? 

Thanks

**Comment by karellm** [comment]
This is natively supported though it is not documented apparently. See the [associated test](https://github.com/i18next/i18next-parser/blob/84d47903ac6a5837ad688358453f394b45161c8d/test/parser.test.js#L732).

**Comment by pinkynrg** [comment]
That's great it works!

I noticed though that once yml files are created, and I run a second command to update the translation files I get an error i write like the following:

```
[error] SyntaxError: Unexpected token a in JSON at position 1
  [write] /Users/francescomeli/Projects/client-web-venv/client-web/client_web_package/assets/yml/i18n/it-IT/translations.yml
```

**Comment by karellm** [comment]
I could pretend that's premium service but you caught me at the right time ;) I'll be online for couple more hours so let me know.

**Comment by pinkynrg** [comment]
Fantastic just made it work. Something weird was going on with npm.

Basically I had to install the package using this `1.0.0-beta33` instead of this `^1.0.0-beta33`.

If I used `^1.0.0-beta33`, `1.0.0-beta9` was installed instead and nothing was working of course. 

Weird.
