### ISSUE TITLE
Disabling separators breaks output

### ISSUE THREAD

**Issue by vincaslt** [i18next/i18next-parser#151]
- Is this a bug or a feature request?
Bug

- What version are you running (`0.x` or `1.x`)? 
i18next-parser@1.0.0-beta34

- Which runner (cli, gulp...)?
CLI

## What I'm trying to do?

I want to use keys as values, but without any characters being interpreted as namespace or key separators.

## How am I doing it?

Here is my config file:

```
module.exports = {
  default: [
    {
      lexer: ['TypescriptLexer', 'JsxLexer'],
      tsOptions: {
        jsx: 'Preserve',
        target: 'esnext'
      }
    }
  ],
  input: ['src/**/*.{ts,tsx}'],
  keySeparator: false,
  locales: ['en', 'lt'],
  namespaceSeparator: false,
  output: 'public/locales/$LOCALE/$NAMESPACE.json',
  useKeysAsDefaultValue: true,
  verbose: true
}
```

The command I'm running:

```
i18next --config i18next-parser.config.js
```

## What was the result?

The keys I am getting are all in the form of:

```
{
  "Enter city": "translation__!NO_KEY_SEPARATOR!__Enter city"
}
```

## What was I expecting?

```
{
  "Enter city": "Enter city"
}
```

I think the problem might be here: https://github.com/i18next/i18next-parser/blob/11cb4590ca02e694a8ad717f759f648fa39d704f/src/helpers.js#L14

It ignores whatever is set in the config it seems and just uses dots. Making this change worked for me:

```
newValue = entry.key.substring(entry.key.indexOf(separator) + separator.length, entry.key.length);
```

**Comment by karellm** [comment]
Thanks for the pointer and PR. This was fixed in `1.0.0-beta35`.
