### ISSUE TITLE
Using same namespace in different parser instances

### ISSUE THREAD

**Issue by nickasd** [i18next/i18next-parser#159]
I have a Gulp task which runs 2 different `i18next-parser` instances, each one for a different folder representing a different namespace. Let's call these namespaces/folders `A` and `B`, which are also run in this order in the Gulp task. Now in namespace `B` I would like to reference a key from namespace `A`, but unfortunately when running the Gulp task the json file generated by parsing folder `A` is overwritten by the few references to namespace `A` in folder `B`. Remember, the parser instance for folder `B` cannot know that the parser instance for folder `A` has just been run.

My question is: is this a scenario that this framework could possibly address? The only solution that comes to my mind right now is that supporting it would require removing the generation of the `_old` files, so that each parser instance can merge its results with any existing json file. (Are these `_old` files still a wanted feature? Most people will probably use git anyway.)

**Comment by nickasd** [comment]
Now I think this radical solution may not be necessary. Since all references to namespace `A` from folder `B` should already be defined in folder `A`, it would be sufficient to have an option `skipNonDefaultNamespaceKeys` when running the parser for folder `B`. Optionally, the parser could check if all the references to the non default namespace are really defined in the previously generated json file of that namespace. What do you think? I could make a PR.

**Comment by karellm** [comment]
I realize I never answered. This seems to me as a very far fetch use case and I'm not really sure I fully understand the point. I will close this for now and if you happen to still need it, feel free to reopen and argue for it.
