### ISSUE TITLE
Support for shared namespace or ignoring a namespace

### ISSUE THREAD

**Issue by blmoore** [i18next/i18next-parser#160]
- Is this a bug or a feature request? Feature request
- What version are you running (`0.x` or `1.x`)? `1.x`
- Which runner (cli, gulp...)? CLI

## What I'm trying to do?

* Use i18next-parser with a common namespace, shared across langs, alongside their own namespaces, e.g.:
```
locales/common.json
locales/en/translation.json
locales/zh/translations.json
...
```

The rest of the i18next stack supports this pattern but i18next-parser doesn't seem to.

## How am I doing it?

in TSX:

```tsx
t('common:foo')
```

## What was the result?

```
locales/en/translation.json
locales/en/common.json
locales/zh/translations.json
locales/zh/common.json
...
```

## What was I expecting?

Ideally I could supply my own ns resolution function, e.g.:

```js
(lang, namespace) => ns === 'common' ? 'locales/common.json' : 'locales/$LOCALE/$NAMESPACE.json
```

Alternatively, if an `ignoredNamespaces` option is a lot cheaper to implement (#116?) that could work too.

**Comment by karellm** [comment]
I'm not opposed to the idea but I will not implement it. I'm closing this for now, if you want to work on it, I invite you to open a PR.
