### ISSUE TITLE
Allow defining custom lexers

### ISSUE THREAD

**Issue by korsarNek** [i18next/i18next-parser#162]
At the moment, the available lexers are restricted by the entries in the lexersMap and I think there is currently no way to extend this list.

I wanted to add a lexer for Vue-Templates, because the normal javascript lexer isn't able to parse the i18n namespace on the component level.

```
<template>
    <div>{{ $t('test') }}</div>
</template>
<script>
export default {
    i18nOptions: {
        namespaces: ['ns-test']
    }
};
</script>
```

**Comment by karellm** [comment]
You are welcome to make a PR with new lexers.

**Comment by karellm** [comment]
Closing by lack of activity. Feel free to reopen to reactivate this.
