### ISSUE TITLE
Parsing translation keys from comment blocks

### ISSUE THREAD

**Issue by blmoore** [i18next/i18next-parser#166]
- Is this a bug or a feature request? Potential bug
- What version are you running (`0.x` or `1.x`)? 1.x
- Which runner (cli, gulp...)? cli

## What I'm trying to do?

As described in https://github.com/i18next/i18next-parser/issues/83#issuecomment-375907625, I have a dynamically generated translation key and so am hard-coding all possible values the key will hold at runtime in a comment block, hoping they will be picked up by i18next-parser.

## How am I doing it?

```tsx
{
// t("link.firstlink")
// t("link.secondlink")
}
<SomeElement content={t(`link.${variable}`)} />
```

Here is my config file:

```js
const injectAcornStaticClassPropertyInitializer = require("acorn-static-class-property-initializer/inject");
const injectAcornStage3 = require("acorn-stage3/inject");
const injectAcornEs7 = require("acorn-es7");

module.exports = {
  contextSeparator: "_",
  createOldCatalogs: true,
  defaultNamespace: "translation",
  defaultValue: "",
  keepRemoved: false,
  keySeparator: ".",
  lexers: {
    js: ["JavascriptLexer"], 
    jsx: ["JsxLexer"],
    mjs: ["JavascriptLexer"],
    ts: ["TypescriptLexer"],
    tsx: [
      {
        lexer: "TypescriptLexer",
        attr: "i18nKey", // Attribute for the keys
        tsOptions: {
          jsx: "Preserve",
          target: "esnext"
        },
        acorn: {
          injectors: [
            injectAcornStaticClassPropertyInitializer,
            injectAcornStage3,
            injectAcornEs7
          ],
          plugins: {
            staticClassPropertyInitializer: true,
            stage3: true,
            es7: true
          }
        }
      }
    ],
    default: ["TypeScriptLexer"]
  },
  lineEnding: "auto",
  locales: ["en"],
  namespaceSeparator: ":",
  output: "public/locales/$LOCALE/$NAMESPACE.json",
  input: undefined,
  reactNamespace: false,
  useKeysAsDefaultValue: false,
  verbose: true
};

```

The command I'm running:

```
i18next 'src/components/**/*.tsx' --config ./i18n-parser.config.js
```

## What was the result?

No translation keys detected for `link`

## What was I expecting?

Translation keys added from comments:

```json
{
  "link": {
    "firstlink": "",
    "secondlink": ""
  }
}
```

**Comment by blmoore** [comment]
Anyone solved this? Maybe I misunderstood [your comment](https://github.com/i18next/i18next-parser/issues/83#issuecomment-375907625) @karellm?

**Comment by karellm** [comment]
It should work. I suspect that it's yet another bug in acorn. Please see this for more info: https://github.com/i18next/i18next-parser/issues/155#issuecomment-536237811

You are welcome to tackle this if you want.

**Comment by karellm** [comment]
#180 was merged and `1.0.0-beta36` published. Acorn is dead, long live Typescript.

**Comment by tienpham94** [comment]
@karellm I have the same issue, I can't parse translation keys from comments, even though I added the comments already
```
// t("key.firstName")
// t("key.lastName")
```

**Comment by karellm** [comment]
I believe this is still broken indeed. See here https://github.com/i18next/i18next-parser/issues/83

A PR is welcome.
