### ISSUE TITLE
Cannot override default name of functions to parse

### ISSUE THREAD

**Issue by Niklas81** [i18next/i18next-parser#181]
Possible bug when running i18next-parser@1.0.0-beta35 through Gulp.

## What I'm trying to do?
I'm trying to make the parser parse functions that uses `__` rather than `t` for defining key names that should be localized.

## How am I doing it?
Here is my `gulpfile.js` file:

```
'use strict'
const gulp = require('gulp')
const i18nextParser = require('i18next-parser').gulp

gulp.task('default', function() {
  return gulp.src('client/components/*')
    .pipe(new i18nextParser({
      locales: ['en','sv'],
      verbose: true,
      functions: ['__'],
      output: 'locales/$LOCALE.json'
    })
    .on('warning:variable', (path, key) => {console.log(path, key)}))
    .pipe(gulp.dest('./'))
})
```
Contents of client/components/test.js

```
var t = () => {}
var __ = () => {}

t('test1')
__('test2')
```

The command I'm running:

```
gulp
```

## What was the result?

First run with no existing catalog files makes the following output in console:
```
Parsing /path/folder/client/components/test.js

Parsed keys: 1

[en] translation

Added keys: 1
Restored keys: 0
Removed keys: 0

[sv] translation

Added keys: 1
Restored keys: 0
Removed keys: 0
```
Contents of generated files `locales/en.json` and `locales/sv.json`:

```
{
  "test1": ""
}

```

## What was I expecting?

I was expecting the contents of generated files `locales/en.json` and `locales/sv.json` to be:

```
{
  "test2": ""
}

```

## Conclusion
Anything in the attribute `functions` passed to `new i18nextParser()` seems to be ignored. Have tried using both a string with just `'__'` as well as an array with one or multiple function names. Have also tried passing this as:
```
js: [{
      lexer: 'JavascriptLexer',
      functions: ['__']
}]      
```
but to no avail. Am I doing something wrong? Have also tried in previous version (1.0.0-beta34) as well as 0.13.0. Nothing works.

**Comment by Niklas81** [comment]
Also, just realized that it seems to ignore the `.on('warning:variable', (path, key) => {console.log(path, key)}))` bit as well, though that is of lesser importance to me.

**Comment by vincaslt** [comment]
I believe `functions` is a lexer parameter, so your config should look more or less like this:

```
{
  locales: ['en', 'sv'],
  verbose: true,
  lexers: {
    js: [
      {
        functions: ['__'],
        lexer: 'JavascriptLexer'
      }
    ]
  },
  output: 'locales/$LOCALE.json'
}
```

**Comment by Niklas81** [comment]
Thanks, much appreciated! :+1:
