### ISSUE TITLE
Do we have support for ignore the function and variable?

### ISSUE THREAD

**Issue by MartinMxnn** [i18next/i18next-parser#183]
Firstly, really thx for the update which removes the acron and my last issue is solved.

And do we have or could we add another config option for ignoring the t function contains variable or function? I guess it may be useful.

[error] i18next-parser does not support variables in translation functions, use a string literal: t(capitalization(this.props.pathname.slice(1)

**Comment by karellm** [comment]
I'm not sure why you closed the issue? Did you find a solution to it? 

In all cases, you are welcome to submit a PR with any improvement.
