### ISSUE TITLE
i18next doesn't generate plural forms when count is present

### ISSUE THREAD

**Issue by jmccarrell-lmi** [i18next/i18next-parser#185]
- Is this a bug or a feature request? Feature
- What version are you running (`0.x` or `1.x`)? 
- Which runner? cli

## What I'm trying to do?

get plural forms when i specify count

## How am I doing it?

How to do this?
if { count } exists, then add `_plural` key (note: if ONLY count: with greater than 1, then don't include BASIC key).

**Comment by vincaslt** [comment]
Yeah, the same for me. I see that it says `Plural: keys of the form key_plural and key_plural_0` but I can't find it ever being implemented looking through commit history. I think this is a nice feature to have, will try to implement it.

**Comment by vincaslt** [comment]
From looking at the code it seems that if you add plurals manually, it wouldn't override, but it doesn't have any logic to add them automatically when needed.
