### ISSUE TITLE
parsing the t function returns a single empty key

### ISSUE THREAD

**Issue by miluxmilux** [i18next/i18next-parser#187]
- Is this a bug or a feature request?
Bug

- What version are you running (`0.x` or `1.x`)? 
1.0.0-beta36

- Which runner (cli, gulp...)?
cli

## What I'm trying to do?

Extract keys out of my React App

## How am I doing it?

Here is my config file (nothing special):

```
{
  locales: ['en', 'fr'],
  output: 'public/locales/$LOCALE.json',
  input: 'src/**/*.{ts,tsx}',
}
```

The command I'm running:

```
i18next -c myconfigfile.js
```

## What was the result?

i18next-parser copies all my keys to the _old.json file and generates a file with one key
```
{
" ": ""
}
```

## What was I expecting?
i18next to parse all my keys. The problem code seems to be this line: 
```js
<TablePagination
//...
{...(rows.length > 10 ? { labelRowsPerPage: t('Displayed results: ') } : { labelRowsPerPage: '' })}
//...
/>
```

If I use the Trans component instead of the t function, all is working great. Not sure why?

Thanks

**Comment by vincaslt** [comment]
Could I get more of the code, or better yet a small reproducible example of the bug? From the looks of it, it should work.

**Comment by miluxmilux** [comment]
Hey vincaslt, thanks for your answer. The problem was due to the use of the ":" character in my key. I thought that i18next-parser would get the namespaceSeparator from the main i18next-config. Once I specified an other character in the i18next-parser config file with `namespaceSeparator: '~',`, it worked great.

**Comment by vincaslt** [comment]
You can also specify `false` to not use any.
