### ISSUE TITLE
The word "false" in a string breaks the parser

### ISSUE THREAD

**Issue by dougsmith1000** [i18next/i18next-parser#189]
- Is this a bug or a feature request?
Bug
- What version are you running (`0.x` or `1.x`)? 
0.13.0
- Which runner (cli, gulp...)?
cli

## What I'm trying to do?
Extract a string that contains the word "false". 

## How am I doing it?
My command:
`i18next ./src --fileFilter *.js,*.jsx -r --ignore-variables -o ./src/locales -c false -k false -s false -n common -l de_DE,es_LA,fr_FR,pl_PL,pt_BR,ru_RU,tr_TR`

## What was the result?

 reaches the word "false" in the string, it creates a new json file that it names with the portion of the string that preceded "false". 

When trying to extract the following: "(a) are incomplete or unclear; (b) violate any applicable laws, including without limitation, infringement of intellectual property; (c) contain fraudulent, false, or misleading information; or (d) are otherwise detrimental or damaging.",

An additional file is created that has the file name:
  `(a) are incomplete or unclear; (b) violate any applicable laws, including without limitation, infringement of intellectual property; (c) contain fraudulent, .json`.

The full string is missing from the common.json file that is normally created and contains the rest of the strings. 

## What was I expecting?

A regular text extraction into a new common.json file.

**Comment by vincaslt** [comment]
Could you give a code example and the result you're getting, so I could check?

**Comment by karellm** [comment]
I'm closing by lack of activity, please reopen if you can provide the information asked by @vincaslt
