### ISSUE TITLE
additional seperator config option

### ISSUE THREAD

**Issue by raygerrard** [i18next/i18next-parser#190]
- Is this a bug or a feature request? Feature request
- What version are you running (`0.x` or `1.x`)? Latest
- Which runner (cli, gulp...)? Cli

## What I'm trying to do?

I would like to be able to use a namespaceSeperator and keySeperator only when manually providing a key as an attribute such as:

```
<Trans i18nKey='mainpage:heading.description'></Trans>
```

When using plain text translations I would like to ignore the seperators. This way I can have default text translations but still able to separate pages into namespaces explicitly. Currently I can only disable namespaceSeperator and keySeperator to prevent issues such as:

```
<Trans>
Status: Loading...
</Trans>
```

Ideally example 1 would be placed in its own translation file mainpage.json vs the second example being placed in the default translation file with the key as the text string.

I have not been able to find a way to configure this if it is currently possible.

**Comment by karellm** [comment]
This is not possible indeed. I'm not keen to add this feature as it complicated the options. My recommendation is that you use a separator that is not part of common language. You can maybe double the colon like so `<Trans i18nKey='mainpage::heading.description'></Trans>` which will prevent your issue.
