### ISSUE TITLE
i18next -c path/to/config.js is not working

### ISSUE THREAD

**Issue by externuz** [i18next/i18next-parser#193]
- Is this a bug or a feature request?
bug
- What version are you running (`0.x` or `1.x`)? 
1.0.0-beta37
- Which runner (cli, gulp...)?
CLI

## What I'm trying to do?
Im trying to run i18next-parser with specified config file

## How am I doing it?

`i18next -c /config/i18next/help/config.js`
`i18next -c ./config/i18next/help/config.js`
`i18next -c config/i18next/help/config.js`

## What was the result?

Config file does not exist: /config/i18next/help/config.js
Config file does not exist: ./config/i18next/help/config.js
Config file does not exist: config/i18next/help/config.js

## What was I expecting?

Expecting to successfully extract translations

**Comment by externuz** [comment]
Ok, I found a reason. I have two config files:

config/i18next/help/config.js
```
import configGlobal from "../config.js";

module.exports = {
  ...configGlobal,
  input: ["src/modules/help/**/*.{ts,tsx}"],
  output: "public/locales/$LOCALE/help.json",
};
```

and 

config/i18next/config.js (as main config)
```
module.exports = {
  defaultNamespace: "translation",
  lexers: {
    ts: [{ lexer: "JavascriptLexer" }],
    tsx: [{ lexer: "JsxLexer" }],
    default: ["JavascriptLexer"],
  },
  keySeparator: false,
  locales: ["en", "ru"],
  sort: true,
};
```

As I said early, error looks like file does not exist, but actually the error is that `import` syntax is bad. If I changed it to `const configGlobal = require("../config.js");` it works fine.

**Comment by kirrg001** [comment]
I was running into the same problem today.

CLI said

`Config file does not exist: /path/to/config`

But my actual problem was, that my require path to a JSON file was wrong. Would be great if the CLI would not hide the actual error. Thanks!

**Comment by karellm** [comment]
This will be part of `1.0.3`

**Comment by khodich-dmitriy** [comment]
Its helped to me. Just add the empty space before i18next-parser.config
<img width="525" alt="Screenshot 2020-11-11 at 18 30 10" src="https://user-images.githubusercontent.com/18570283/98830861-efd82880-244b-11eb-8aac-f49ba00cc11b.png">
