### ISSUE TITLE
change the translation function

### ISSUE THREAD

**Issue by spiderchi** [i18next/i18next-parser#204]
- Is this a bug or a feature request? bug
- What version are you running (`0.x` or `1.x`)? Latest 
- Which runner (cli, gulp...)? cli, gulp both

## What I'm trying to do?
I would like to use different translation function.

## How am I doing it?
i18next /path/to/file/or/dir -f T

Here I would like to replace 't' with 'T', but it do not allow me to use 'T'.

**Comment by karellm** [comment]
`-f` is not a valid option of the CLI. Please read the docs to use the options via a config file.
