### ISSUE TITLE
Custom output JSON format

### ISSUE THREAD

**Issue by kirrg001** [i18next/i18next-parser#211]
- Is this a bug or a feature request?
Maybe a feature request or a help question.

- What version are you running (`0.x` or `1.x`)? 
1.0.2

- Which runner (cli, gulp...)?
gulp

## What I'm trying to do?

```
<p>{t("app:headline"), { description: "Max 160 chars" })}</p>
```

app.en.json
```
{
   "headline": {
       "message": "",
       "description": "Max 160 chars"
   }
}
```

## How am I doing it?

I cannot find a way to do it. Went through almost all issues and docs, but there is no hint.
Trying to pass on validation hints for translators as a description field.
Any idea how to do that?

## What was the result?

...

## What was I expecting?

...

**Comment by karellm** [comment]
Hey, I guess that would be a feature request but I don't really have time to code anything like that. If you can explain why you need this, I'd be happy to review a PR.

**Comment by kirrg001** [comment]
> If you can explain why you need this

Trying to pass on validation hints for translators as a description field.
Workflow improvements. Having a translator translating keys, sometimes breaks layouts. If we can forward restrictions in some way, we would improve development time.

>  I'd be happy to review a PR.

Any hint where to look and where to change this? I don't know the code base at all :)

**Comment by karellm** [comment]
I'll review a PR. The codebase is quite simple to get into. You have some [guidelines here](https://github.com/i18next/i18next-parser/blob/master/docs/development.md).

The biggest complexity is that you need to make sure every lexer will extract the information properly. Then you probably want to do something [around here](https://github.com/i18next/i18next-parser/blob/master/src/transform.js#L229) to make sure the data is available in the catalog.

**Comment by kirrg001** [comment]
Will do in a couple of days. Thanks 👍

**Comment by kirrg001** [comment]
Just realised that

```
<p>{t("app:headline")}</p>
```

```
{
   "headline": {
       "message": ""
   }
}
```

is not supported using an option right now. Cannot find a test for this. Am I right?

I would suggest to first make this possible and then add support for other custom fields, which you can configure to pass through. Let me know what you think 😀

**Comment by karellm** [comment]
That's correct, that would need to be an option since it would be a breaking change. It might impact some parts of the code that rely on checking that `headline` in your example is a string. Might be worth double checking that too.
