### ISSUE TITLE
Support variables in translation function

### ISSUE THREAD

**Issue by simoneb** [i18next/i18next-parser#215]
- Is this a bug or a feature request?

Feels like a fairly common use case, so I believe it's a bug.

- What version are you running (`0.x` or `1.x`)? 

1.0.3

- Which runner (cli, gulp...)?

CLI

## What I'm trying to do?

Generate the output for non-literal translation keys in React components.

```
const key = 'some_key'
const t = useTranslation()

return <Comp prop={t(some_key)} />
```

## How am I doing it?

Here is my config file:

```
{
  output: 'translation-keys.yml',
  input: ['src/lib/**/*.jsx'],
}
```

The command I'm running:

```
i18next
```

## What was the result?

There is no translation key with key `some_key`

## What was I expecting?

There is a translation key with key `some_key`

**Comment by karellm** [comment]
Not a bug and not happening as it would complicate the lexers too much when it is even possible. Often when a variable is used, it's not assigned in the same file and there is no way to know what it even resolve to. This parser reads static files, there is no runtime. If you want to do that, you need to add a comment in your code:

```jsx
const key = 'some_key'
const t = useTranslation()

return <Comp prop={t(some_key)} />

// t('some_key')
```

**Comment by karellm** [comment]
I would add that it [should throw you an error](https://github.com/i18next/i18next-parser/blob/master/test/parser.test.js#L1228) and if that's not the case, that would be a bug.

**Comment by simoneb** [comment]
> I would add that it [should throw you an error](https://github.com/i18next/i18next-parser/blob/master/test/parser.test.js#L1228) and if that's not the case, that would be a bug.

No error thrown and no warning even in verbose mode.

**Comment by karellm** [comment]
I've tested and it works for me with your file. Please open a PR with a failing test case so I can look at it.

**Comment by simoneb** [comment]
> I've tested and it works for me with your file. Please open a PR with a failing test case so I can look at it.

By works you mean it's throwing an error?

**Comment by karellm** [comment]
Yes it does throw an error and it logs it to the console when `verbose: true`

**Comment by macfanatic** [comment]
Was investigating this issue just now: so the recommended way is to just use a comment to translate the key?

```typescript
import React from "react";
import { Text } from "react-native";
import { useTranslation } from "react-i18next";

import { SOME_KEY } from "./anotherFile";
// t('SOME_KEY_ACTUAL_VALUE')

export default function MyComponent() {
  const { t } = useTranslation();

  return (
    <Text>{t(SOME_KEY)}</Text>
  );
}
```

I'm considering just using the comment approach on the line immediately after defining the exported constant in our case, but I can't get the comment approach to work no matter where I place it in our codebase.

**Comment by karellm** [comment]
Well I believe you are right, it doesn't work anymore since we've moved to typescript for our lexers. @vincaslt do you know if it would let us parse comments?

**Comment by macfanatic** [comment]
I managed just by referencing it directly, not ideal but works.

From my above example:

```typescript
// In source file
import i18n from "i18next";

export const SOME_KEY = "SOME_KEY";
I18n.t("SOME_KEY");
```

```typescript
// In my component
import { SOME_KEY } from "./anotherFile";
```

**Comment by simoneb** [comment]
We're considering to contribute to the parser with support for the following logic:

> if the variable used by the translation function resolves to a constant, which references a primitive (hence immutable) value, then resolve the value rather than ignoring it

What do you think @karellm?

**Comment by karellm** [comment]
@simoneb I like the idea, could you also look into parsing comments while at it? In all cases, feel free to open a PR and thanks for the contribution!

@macfanatic Yes, that's because comments are simply not parser atm but regular code still is. It's actually an ok solution even though not super elegant.

**Comment by vincaslt** [comment]
I don't see any code in the lexer before rewrite that would parse the translations from comments. Acorn parser AST ignores comments altogether at https://astexplorer.net

I can try to make the comments work though

**Comment by karellm** [comment]
@vincaslt I believe it worked beforer Acorn when the parser was basically complex regexes I had handwritten. We've come a long way since then!

**Comment by simoneb** [comment]
I finally got around to spending some time on introducing simple support for constant variables initialized to string literals, which are safe to replace as they can't change.

I'd appreciate some feedback on the PR: #234
