### ISSUE TITLE
How to tell parser to ignore default values in t function?

### ISSUE THREAD

**Issue by kirrg001** [i18next/i18next-parser#216]
- Is this a bug or a feature request?

Help question

- What version are you running (`0.x` or `1.x`)? 

1.x

- Which runner (cli, gulp...)?

CLI

## What I'm trying to do?

How to tell i18nparser to **not** use the t function default value?

```
t("key", "test")
```

```
t("key", {defaultValue: "test"})
```

results in

en.json
```
{
   key: "test"
}
```

But i want

en.json
```
{
   key: ""
}
```

**Background**: Default values are very useful for developers when working on MVP. Parsing the keys and pushing them to a third party translation service **including** default values, **won't** mark translation keys as "untranslated"!

---

This is my parser config

```
  createOldCatalogs: true,
  defaultNamespace: "common",
  namespaceSeparator: ":",
  defaultValue: "",
  indentation: 2,
  lexers: {
    js: ["JsxLexer"],
    default: ["JsxLexer"],
  },
  lineEnding: "auto",
  locales: locales,
  output: "./public/locales/$LOCALE/$NAMESPACE.json",
  input: ["./**/*.js"],
  reactNamespace: true,
  useKeysAsDefaultValue: false,
  verbose: true,
  keepRemoved: false,
```

**Comment by karellm** [comment]
I'm confused by this, if you [look at the tests,](https://github.com/i18next/i18next-parser/blob/master/test/parser.test.js#L11) it doesn't provide a default value by default. I also ran a test with your options and it seemed to work just fine. 

Could you provide a failing test case?

**Comment by kirrg001** [comment]
Sorry if I wasn't clear.

> it doesn't provide a default value by default

Not having said that :)

I've asked how to disable using the t functions default value if defined by developer.

I add this to my code as a developer

```t("headline", {defaultValue: "This is a headline"})```

And i18next Parser will create

```
{
  "headline": "This is a headline"
}
```

I would like to disable this and get an empty string instead. Is this possible using a parser option? Or is this a feature request?

I need it because I am working with third party providers, which do not like default texts and mark my keys as "translated", which is wrong.

**Comment by karellm** [comment]
That would be a feature request indeed. I believe I would be ok with a `skipDefaultValues` option. Can you make a PR? 

That would be a better first contribution than your other suggestion as this should be a fairly simple code change.

**Comment by kirrg001** [comment]
Will do thank you!
