### ISSUE TITLE
Parser mangles unicode escape sequences

### ISSUE THREAD

**Issue by mareksuscak** [i18next/i18next-parser#227]
## 🐛 Bug Report

This is probably better explained with an example so here you go:

![image](https://user-images.githubusercontent.com/613647/87720932-fca68180-c7b5-11ea-8e01-05b30adb93de.png)

Notice, how `\u00A0` got turned into a mangled sequence of characters.

## To Reproduce

In order to reproduce, just add `\u00A0` to any of your strings in a translation file and run the parser. This is a unicode escape sequence for a non-breaking space character.

## Expected behavior

The unicode escape sequences must stay intact after parser did its job.

## Your Environment

- *runtime version*: node v12
- *i18next version*: 19.6.0
- *os*: Mac

**Comment by mareksuscak** [comment]
For anyone who picks this up - if there's a better way to add a non-breaking space, I'm all ears. Tried a slew of different approaches and most of them didn't work well.

**Comment by karellm** [comment]
This should be fixed as part of `3.4.0`. Thanks @jamesots for the fix.

**Comment by ricardosouza-logmein** [comment]
Version `i18next-parser@9.1.0` presents the same issue
