### ISSUE TITLE
Include values as default translations

### ISSUE THREAD

**Issue by rhulshof** [i18next/i18next-parser#23]
As already partially discussed in https://github.com/i18next/i18next-parser/issues/13 and related to my implementation as described here http://stackoverflow.com/questions/26561879/i18next-best-practice/26737839?noredirect=1, I wonder if it will be possible to:

Parse `i18n.t('namespace.example', 'Default value');` methods and insert `Default value` into the locales/translation files whenever `namespace.example` is still empy. And do the same for `<span data-i18n="namespace.example">Default value</span>` HTML tags.

I think it is way more easy to translate a JSON file that looks like:

```
"namespace" : {
   "example" : "Default value"
}
```

Than when it looks like:

```
"namespace" : {
   "example" : ""
}
```

Assuming that my implementation works correctly. My generated translation files always contain empty strings like in the latter example.

As a side benefit; then even when a lable is untranslated, the UI will at least show the default value (in most cases the English version) instead of an empty string.

**Comment by sanbor** [comment]
Some of us use keys as default translations. e.g.:

```
"namespace" : {
   "Hello world" : "Hello world"
}
```

But the current behavior is:

```
"namespace" : {
   "Hello world" : ""
}
```

It would be nice to at least have the option to use the key as the value.

**Comment by sourceRS** [comment]
I'm interested in how this could also apply to pluralized values:

```
i18n.t('Hello world', { value: 'Hello world', value_plural: 'Hello planets!' });
```

```
"namespace" : {
   "Hello world" : "Hello world"
   "Hello world_plural" : "Hello planets!"
}
```

or perhaps, if you're using the key as a default value:

```
i18n.t('Hello world', { value_plural: 'Hello planets!' });
```

```
"namespace" : {
   "Hello world" : "Hello world"
   "Hello world_plural" : "Hello planets!"
}
```

**Comment by karellm** [comment]
@sourceRS I'm not actively maintaining this project but I will merge PRs if you feel like tackling it

**Comment by karellm** [comment]
This will be added to #72. Track changes there, closing this for now.
