### ISSUE TITLE
Parser throws an error 'TypeError: Cannot read property 'numbers' of undefined' when locales parameter is present

### ISSUE THREAD

**Issue by NethmiRodrigo** [i18next/i18next-parser#230]
## 🐛 Bug Report

I can't set locales with an array of locales it throws an error  `TypeError: Cannot read property 'numbers' of undefined`  from `node_modules\i18next-parser\dist\transform.js:130:99`. It works perfectly when I remove locales but uses the defaults `en` and `fr`.

## To Reproduce
Here's my config file

```js
module.exports = {
  createOldCatalogs: false,
  // Save the \_old files

  // defaultNamespace: 'translation',
  // Default namespace used in your i18next config

  defaultValue: '',
  // Default value to give to empty keys

  indentation: 2,
  // Indentation of the catalog files

  // see below for more details
  lexers: {
    js: ['JsxLexer'], // if you're writing jsx inside .js files, change this to JsxLexer
    ts: ['JsxLexer'],
    jsx: ['JsxLexer'],
    tsx: ['JsxLexer'],

    default: ['JsxLexer'],
  },

  locales: ['en', 'sin'],
  // An array of the locales in your applications

  output: 'public/locales/$LOCALE/$NAMESPACE.json',
  // Supports $LOCALE and $NAMESPACE injection
  // Supports JSON (.json) and YAML (.yml) file formats
  // Where to write the locale files relative to process.cwd()

  input: ['src/components/**/*.{js,jsx,ts,tsx}'],
  // An array of globs that describe where to look for source files
  // relative to the location of the configuration file

  verbose: true,
  // Display info about the parsing including some stats
};
```

## Expected behavior
To have the translation file written in the locale folders `en` and `sin` as specified in the locales array.

## Your Environment

- *runtime version*: i.e. node v12.16.1
- *i18next version*: 19.1.0
- *os*: Windows
- *Which runner (cli, gulp...)?* cli

**Comment by kristian-puccio** [comment]
I'm also getting the same error but for me it's only happening when I try to extract the `iw` locale.
All other seem to work for me

**Comment by karellm** [comment]
The code shouldn't crash but it's basically because the language you selected isn't know by `i18next`. We use the [plural resolver](https://github.com/i18next/i18next/blob/master/src/PluralResolver.js) to determine how many plurals a language has. I've fixed this by setting a default to 1 plural form for "unknow" languages.

This was deployed as `2.1.3`

**Comment by NethmiRodrigo** [comment]
> The code shouldn't crash but it's basically because the language you selected isn't know by `i18next`. We use the [plural resolver](https://github.com/i18next/i18next/blob/master/src/PluralResolver.js) to determine how many plurals a language has. I've fixed this by setting a default to 1 plural form for "unknow" languages.
> 
> This was deployed as `2.1.3`

So the only soultion would be to use a known language?

**Comment by karellm** [comment]
If you want plural to be determined by the plural resolver, then yes you must use a known language. 

If you don't use a known language, it won't crash anymore and will default to a single plural form.

**Comment by NethmiRodrigo** [comment]
> If you want plural to be determined by the plural resolver, then yes you must use a known language.
> 
> If you don't use a known language, it won't crash anymore and will default to a single plural form.

Gotcha. Thanks! :)
