### ISSUE TITLE
parsing <Trans> in tsx, no value is extracted

### ISSUE THREAD

**Issue by Yuripetusko** [i18next/i18next-parser#231]
##  🐛 Bug Report

Calling  `save-missing` on Trans with new synthax in tsx does not extract values

## To Reproduce 

```
<Trans
                    i18nKey="questionReviews"
                    ns="testimonialsReviews"
                    defaults="Questions or concerns about one of your reviews? Contact us at
                    <a>hello@test.co.uk</a> and we'll
                    be happy to help!"
                    components={{ a: <a href="mailto:hello@test.co.uk">hello@test.co.uk</a>}}></Trans>
```

`"downloadLocizeTranslations": "i18next 'components/**/*.tsx' && locize save-missing --api-key XXX --project-id XXX --format json --path ./public/static/locales"`

```
const i18nConfig = require('./i18n/config');

module.exports = {
  defaultNamespace: i18nConfig.defaultNamespaces[0],
  // Default namespace used in your i18next config

  defaultValue: 'missing value',
  // Default value to give to empty keys

  locales: i18nConfig.supportedLanguages,
  // An array of the locales in your applications

  namespaceSeparator: ':',
  // Namespace separator used in your translation keys
  // If you want to use plain english keys, separators such as `.` and `:` will conflict. You might want to set `keySeparator: false` and `namespaceSeparator: false`. That way, `t('Status: Loading...')` will not think that there are a namespace and three separator dots for instance.

  output: `${i18nConfig.localesPath}/$LOCALE/$NAMESPACE.json`,
  // Supports $LOCALE and $NAMESPACE injection
  // Supports JSON (.json) and YAML (.yml) file formats
  // Where to write the locale files relative to process.cwd()
  createOldCatalogs: false,
  reactNamespace: false,
};

```

And output I get is:

```
{
  "questionReviews": "missing value",
}

```

## Expected behavior

```js
{
  "questionReviews": "Questions or concerns about one of your reviews? Contact us at <a>hello@test.co.uk</a> and we'll be happy to help!"
}

```

## Your Environment

- *runtime version*: i.e. node v12.16.§
- *i18next version*: i.e. 19.6.1
- *i18next-parser*: "2.1.2",
- *react-i18next*: "^11.7.0",
- *os*: Mac
- *any other relevant information*

**Comment by vincaslt** [comment]
I've checked the relevant code, and it seems this case is not handled. Let me know if you'd like to submit a PR for this, or I could fix it sometime soon. For now it seems the only way to override a default value in Trans component is to pass children to it - it will be the default value.

**Comment by Yuripetusko** [comment]
I'm not that familiar with the code yet to know what to change exactly to fix this. 🤔  If I find a time to look into it then I'll submit a PR in next week or so

**Comment by karellm** [comment]
This is deployed as `3.1.0`.
