### ISSUE TITLE
unable to parse keys using i18next pipe

### ISSUE THREAD

**Issue by mmelyp** [i18next/i18next-parser#247]
translation keys in Typescript/javascripts as well as html attributes with data-i18n attribute, are well parsed. The problem is when using a key and a pipe in a html. example:

`<ion-list-header>{{ 'test' | i18next }} </ion-list-header>
`

or even with:

`<p>{{ 'test' | i18next }}</p>
`

the key is not being parsed into the $NAMESPACE.json.

**Comment by karellm** [comment]
I'm not aware of this syntax. You are welcome to open a PR with a fix!

**Comment by karellm** [comment]
Closing by lack of activity
