### ISSUE TITLE
Parser overwrites existing translations

### ISSUE THREAD

**Issue by Ichag** [i18next/i18next-parser#248]
- Is this a bug or a feature request?
Bug
- What version are you running (`0.x` or `1.x`)? 
3.3.0
- Which runner (cli, gulp...)?
gulp 4
## What I'm trying to do?

I'm having existing translation and template files. 
If a key gets added to the template I want to extract it and add it to the existing translation file.

Instead of just adding the new key to the existing file it adds the new key, but also removes all existing translations from the translation file.

It parses the hbs file correctly and extracts the new key, but it also overwrites all other existing translations.

## How am I doing it?

Here is my config file:

```
const files = {
  templates: './src/templates/template.hbs'
}
const dirs = {
  resources: './src/resources'
}

const i18nextDefaultNamespace = 'translations'

const extractI18nKeys = () => {
  return src(files.templates).pipe(
      new i18nextParser({
        locales: i18next.options.preload,
        defaultNamespace: i18nextDefaultNamespace,
        lexers: {
          hbs: [
            {
              lexer: 'HandlebarsLexer',
              functions: ['i18n'], // Array of functions to match
            },
          ],
        },
        output: `locales/$LOCALE/$NAMESPACE.json`,
      }),
  ).pipe(dest(dirs.resources));
};
```

The command I'm running:

```
gulp extractI18nKeys
```

## What was the result?
```
{
  "passwordReset": {
    "passwordResetSuccessEmail": {
      "subTitle": "",
     "subTitle2: ""
  }
}
```
## What was I expecting?
```
{
  "passwordReset": {
    "passwordResetSuccessEmail": {
      "subTitle": "Existing translation",
     "subTitle2: "" // Newly created key
  }
}
```

**Comment by karellm** [comment]
Can you make a reproduceable repo?

**Comment by Ichag** [comment]
The project is here:
https://github.com/Ichag/parser-demo

The gulp job starts at line 66:

**Comment by Ichag** [comment]
If I change the output path
`output: `locales/$LOCALE/$NAMESPACE.json`,`
to something like
`output: `${dirs.locales}/$LOCALE/$NAMESPACE.json`,`
It produces new files under
`src/resources/locale/src/resources/de/translations.json`
Those files contain all translations as expected, but the files are new and not edit the existing ones inline.

**Comment by karellm** [comment]
The `output` option is used to parse the existing catalog and doesn't replace the `dist()`. It seems to me that you should update the path to `${dirs.resources}/$LOCALE/$NAMESPACE.json`. Can you try that and report back?

**Comment by Ichag** [comment]
With that it creates two new files (with empty values inside) instead of updating the existing ones
![image](https://user-images.githubusercontent.com/951372/98938492-42ffb900-24e8-11eb-9cb9-50782132fdea.png)

If I change the path to `${dirs.resources}/locales/$LOCALE/$NAMESPACE.json` it creates files unter `src/resources/src/resources/locales/$LOCALE/translation.json`. Those files include the message keys and translations but exist got newly created instead of updating the existing ones..

Do I unterstand the purpose of this project wrong? As I expect it, it should update the existing catalog and not creating new files.

Do you have an idea? Is this a bug or do I use the project different than expected?

**Comment by karellm** [comment]
I can't figure it out. It might be a bug. You are welcome to open a PR to fix it. I don't currently have the bandwidth to code on this.

**Comment by Ichag** [comment]
Hi, just wanted to let you know that I found an issue in my path configuration.
Using the correct path configuration resolves all translation files correctly and keys are getting added instead of overwritten:
https://github.com/Ichag/parser-demo/commit/d52fe9a540ed580e3e93b39942f1ac987bb48b8f

This ticket can be closed, it is **not** an issue of i19n-parser but in my configuration.
