### ISSUE TITLE
Is there some kind of a cache going on?

### ISSUE THREAD

**Issue by kernelogic** [i18next/i18next-parser#255]
Hello, I tried to run the cli. The first time I generated a json file with content, but later on when I delete the json and re-run the cli again the json is empty. Is it caching what have been parsed somewhere?

**Comment by karellm** [comment]
No there isn't any cache, just an "old" catalog that store previously used keys. Check out the `createOldCatalogs` option. 

As to your issue, I couldn't reproduce, please provide with a test project or more detailed walkthrough.

**Comment by RishiDiwanTT** [comment]
I had the same error, using `verbose` output told having a `:` in the key even with a custom nsSeparator was the issue. This created an empty namespace for me because the colon was at the end of the key. Eg. `t('key:', 'value')`.
