### ISSUE TITLE
Empty Locale Extraction

### ISSUE THREAD

**Issue by joshmeads** [i18next/i18next-parser#258]
I've searched the docs + issues and haven't found how to handle this. Currently, my extracted value is applied to every locale.

## 🚀 Feature Proposal

Add a `sourceLocale` configuration option (string).
Extract keys for all locales in the config array and set the value to `defaultValue` - with the exception of the `sourceLocale`.

## Motivation

I've just switched from Lingui which did this and found it very useful, allows me to configure everything in the source language but pre-generate the markup keys for translators. React-i18next will simply fall back to the source language on null or empty string (if configured to and defaultValue is set as such).

## Example

Given a config of
```js
module.exports = {
  sourceLocale: 'en',
  locales: ['en', 'fr'],
  defaultValue: '',
  input: ['src/pages/**/*.js'],
  output: 'src/locales/$LOCALE/$NAMESPACE.yml',
  lexers: {
    js: ['JsxLexer'],
  },
};
```

And a component of:
```js
export const Footer = () => (
  <footer>
      <p>
        <Trans i18nKey="footer:name">
          HelloWorld Application
        </Trans>
      </p>
      <p>
        <Trans i18nKey="footer:company">
          FooBar Inc.
        </Trans>
      </p>
  </footer>
);

```

I'd expect the following (given a `defaultValue: ''`)

`src/locales/en/footer.yml`
```yml
name: 'HelloWorld Application'
company: 'FooBar Inc.'
```

`src/locales/fr/footer.yml`
```yml
name: ''
company: ''
```

In this example, I could update `name` for `fr` and `company` would simply fall back to `en`.

---

Let me know your thoughts, I'd be willing to work on this if people don't see any obvious issues.

**Comment by karellm** [comment]
I'm not sure I understand the benefit of having the other locales blank. The idea is actually to provide context for translator as to what the content is.
