### ISSUE TITLE
All files are read but some of them ignored and translations inside them not getting parsed in Nextjs.

### ISSUE THREAD

**Issue by Zieu** [i18next/i18next-parser#260]
* Is this a bug or a feature request?
Bug

* What version are you running (0.x or 1.x)?
3.6.0

* Which runner (cli, gulp...)?
cli

## What I'm trying to do?

get all translations parsed

## How am I doing it?

Here is my config file:

``` js
// i18next-parser.config.js
 
module.exports = {
  locales: ["uz", "ru"],
  namespaceSeparator: false,
  keySeparator: false,
  useKeysAsDefaultValue: true,
  verbose: true,
  output: "public/static/locales/$LOCALE/$NAMESPACE.json"
}; 
```
Here is my npm script:
 ``` json
// package.json
"scripts": {
"i18n": "i18next 'src/**/*.{ts,tsx}' [-oc]",
}
```

## What was the result?

After parsing, log said all files were parsed, however, some translations were missing. I noticed that when particular translation is missing, all the others which are in the same file are ignored.

**Comment by karellm** [comment]
Can you make a repo where we can reproduce? It's quite impossible with the information you provided to figure out what is going on.

**Comment by Abror1997** [comment]
setting "sort: true" in config file solves the problem for me @Zieu

**Comment by Zieu** [comment]
> setting "sort: true" in config file solves the problem for me @Zieu

It helped! Thank you.

**Comment by karellm** [comment]
Well I would still appreciate a reproduceable repo  s it doesn't seem to be normal.

**Comment by Zieu** [comment]
> Well I would still appreciate a reproduceable repo  s it doesn't seem to be normal.

I couldn't reproduce the bug in another repo. Can't show the repo where the bug occurred.
