### ISSUE TITLE
Keys from deeply nested files are not present after parse.

### ISSUE THREAD

**Issue by Mottoweb** [i18next/i18next-parser#271]
## 🐛 Bug Report

Parsing using CLI skips keys when folder nesting is deep.

## To Reproduce

Running CLI command like `i18next 'src/scenes/ServiceDashboard/**/*.{js,ts,jsx,tsx}'` where `ServiceDashboard` is a folder with lots of other folders.
I have a file there `containers/Dashboard/index.js` with the keys that I find missing after the parse.
In the CLI output, I can see the file as being read.

When doing `i18next 'src/scenes/ServiceDashboard/containers/Dashboard/**/*.{js,ts,jsx,tsx}'`, i.e. a few folders down the hierarchy, I get the expected parse results in my json.

Parser config
```js
module.exports = {
  defaultNamespace: 'parserDefaultNs',
  defaultValue: '',
  indentation: 2,
  lexers: {
    js: ['JavascriptLexer'],
    ts: ['JavascriptLexer'],
    jsx: ['JsxLexer'],
    tsx: ['JsxLexer'],
    default: ['JavascriptLexer'],
  },

  locales: ['en', 'de'],
  namespaceSeparator: ':',

  output: 'locales/$LOCALE/$NAMESPACE.json',
  sort: false,
  skipDefaultValues: false,
  useKeysAsDefaultValue: false,
  verbose: false,
  failOnWarnings: false,
  customValueTemplate: null,
  keySeparator: '.',
};
```

## Expected behavior

Running CLI command for deeply nested folder would parse keys as expected.

## Your Environment

- node v14.0.0
- *os*: Mac

**Comment by Mottoweb** [comment]
Ok i have a little update here which did not make any sense to me, maybe someone could help.

When using `src/**/*.js` or `src/**/*.{js,ts}` glob i get the keys that i expect, when using `src/**` or `src/**/*.{js,ts,jsx}` i dont get certain keys parsed, which are in js file. The folder does not contain any other file extension apart from `js`.

**Comment by Mottoweb** [comment]
With a verbose options set to true i can see that the correct file is being parsed: `Parsing /Users/fedorbuturlin/dev/audienzz/js/apps/console/src/scenes/ServiceDashboard/containers/Dashboard/index.js`

Result: 
```
[en] serviceDashboard

Unique keys: 489 (489 with plurals)
Added keys: 489
Restored keys: 0
Removed keys: 0

Found translation key already mapped to a map or parent of new key already mapped to a string: 
Found translation key already mapped to a map or parent of new key already mapped to a string: FLIGHT_NAME
[de] serviceDashboard

Unique keys: 489 (489 with plurals)
Added keys: 489
Restored keys: 0
Removed keys: 0
```

But the translation file itself contains only `438` keys. Any help on this please?

**Comment by Mottoweb** [comment]
#260

**Comment by karellm** [comment]
@Mottoweb I've tried to reproduce this issue without success. If you can make a repo it would be helpful.

**Comment by Mottoweb** [comment]
@karellm ok I recreated a part of the repo here, I was also able to debug it a little further, it seems that it does not work as expected when I provide it with absolute paths, i.e. /users/etc

here is the repo: https://github.com/Mottoweb/i18next-parser-issue-replica

steps to reproduce:

1. Run `node nameSpaceTool.js` which will run the gulp pipe with the correct absolute path (note you can run it as a CLI as well, it's just commented out in nameSpaceTool.js`
2. Check `serviceDashboard.json` in `./locales`
3. `DASHBOARD` key is not present from `./src/scenes/ServiceDashboard/containers/Dashboard/index.js`

Steps to get the correct result:
Use `sort: true` in config
or
Run `i18next 'src/scenes/ServiceDashboard/**/*.{js,ts.tsx}'` (note: this did not work in original repo, only in this recreated repo)

I really hope this helps, let me know if you need something else please.

**Comment by karellm** [comment]
@Mottoweb Thanks but it looks like the repo might be private.

**Comment by Mottoweb** [comment]
@karellm oops, just made it public
