### ISSUE TITLE
Support for extended handlebars helper

### ISSUE THREAD

**Issue by limdauto** [i18next/i18next-parser#29]
As described in http://i18next.com/pages/doc_templates.html, to use context and option variables in Handlebars, we need an extended helper

```
Handlebars.registerHelper('tr', function(context, options) { 
   var opts = i18n.functions.extend(options.hash, context);
   if (options.fn) opts.defaultValue = options.fn(context);

   var result = i18n.t(opts.key, opts);

   return new Handlebars.SafeString(result);
});
```

Is it sensible to support this along with the standard `t`?

**Comment by limdauto** [comment]
I suppose I can write my own parser, but I would imagine that many people will need this `tr` to support pluralization.

**Comment by karellm** [comment]
Support would be great but I am currently limited in time. 

The easy solution is to use the `regex` option and create your own. If you have some more time, a PR would be welcome!

**Comment by antwan1986** [comment]
I'm in the exact same boat as of today, so if someone does invent a regex that works, please post!

**Comment by limdauto** [comment]
Sorry for not getting back a bit late. I have thought this through. I think the `{{tr }}` setup is a bit mad. I have normalized everything to work with a single `{{t }}`. Work for me in my case.

**Comment by karellm** [comment]
I can't see any use case that could not be handled with `{{t }}`. I'm currently rewriting this package and the new Handlebar lexer will support things like `{{t "key" defaultValue="bla"}}`. You can track the progress at #72.

If this is every an issue, please make a case for it and I will consider it. Until then, I'm closing this.
