### ISSUE TITLE
Configurable `pluralSeparator`

### ISSUE THREAD

**Issue by queicherius** [i18next/i18next-parser#300]
## 🚀 Feature Proposal

I would like to be able to configure the plural separator, just like the key, namespace, and context separator.

## Motivation

I use a different plural separator than `_` to prevent potential conflicts with the keys, since I use natural keys that might include that in the text.

## Example

```ts
pluralSeparator: '___',
```

**Comment by karellm** [comment]
You are welcome to make a PR, I'll review and merge it.
