### ISSUE TITLE
Period at end of Trans tag is missing, causing i18next not to translate

### ISSUE THREAD

**Issue by cdaycmc** [i18next/i18next-parser#306]
## 🐛 Bug Report

(was reported at https://github.com/i18next/react-i18next/issues/1312)

Period at end of Trans tag is missing after auto-extraction, causing i18next not to translate.

eg. `<Trans>Here is some text to translate.</Tran>`
will auto-extract to the json as
```
{
  "Here is some text to translate": "Here is some text to translate."
}
```

## To Reproduce

[translate.zip](https://github.com/i18next/i18next-parser/files/6413021/translate.zip)

```
function App() {
  const { t, i18n } = useTranslation();
  return (
    <I18nextProvider i18n={i18n}>
      <a
        href="#"
        onClick={() => {
          i18n.changeLanguage("en");
        }}
      >
        en
      </a>
      |
      <a
        href="#"
        onClick={() => {
          i18n.changeLanguage("pt");
        }}
      >
        pt
      </a>
      <br />
      <Trans>Here is a button</Trans>
      <br />
      <MyButton label={<Trans>I Change</Trans>} />
      <MyButton label={t`I Change`} />
      <Trans>I Change</Trans>
      <br />
      <span>
        <Trans>
          But here is something that has <a href="#">a link</a> in the middle of
          the text.
        </Trans>
        xx
      </span>
    </I18nextProvider>
  );
}

const MyButton = ({ label }) => {
  return (
    <button>
      <span>{label}</span>
    </button>
  );
};
```

Command to extract
`npx i18next 'src/**/*.jsx'`

## Expected behavior

`<Trans>Here is some text to translate.</Tran>`
will auto-extract to the json as
```
{
  "Here is some text to translate.": "Here is some text to translate."
}
```

## Your Environment

- *runtime version*: v14.15.3
- *i18next version*:20.2.2
- *os*: Windows
- i18next-parser: 3.11.0

**Comment by karellm** [comment]
Have you tried setting `keySeparator: false`? Here is from the README:

> If you want to use plain english keys, separators such as `.` and `:` will conflict. You might want to set `keySeparator: false` and `namespaceSeparator: false`. That way, `t('Status: Loading...')` will not think that there are a namespace and three separator dots for instance.

**Comment by cdaycmc** [comment]
That worked.  Having a bad day not reading :(
