### ISSUE TITLE
Found same keys with different values

### ISSUE THREAD

**Issue by ajsaraujo** [i18next/i18next-parser#333]
What does that warning mean? "Found same keys with different values"

When I got the warning, I expected it to be about  key having more than one occurrence in a translation file, but it didn't. 

Can someone clarify this for me?

[This](https://github.com/ajsaraujo/Rocket.Chat/tree/chore/i18next-parser) is the project I ran the parser on.

**Comment by karellm** [comment]
I've added some documentation about the warning in the readme: https://github.com/i18next/i18next-parser#events

The warning should be of the form `Found same keys with different values: THEKEY`. If you look in your code for `THEKEY`, you can make sure they all have the same value.
