### ISSUE TITLE
TAPi18n calls not being caught by parser

### ISSUE THREAD

**Issue by ajsaraujo** [i18next/i18next-parser#334]
## 🐛 Bug Report

I'm trying to use i18next-parser to get all translation keys being used in [this project](https://github.com/ajsaraujo/Rocket.Chat/tree/chore/i18next-parser). However, some of the `TAPi18n.__` calls are not being caught. The ones in [this file](https://github.com/ajsaraujo/Rocket.Chat/blob/chore/i18next-parser/app/user-data-download/server/exportDownload.js#L24), for example. Following the steps suggested in [EXAMPLEs.md](https://github.com/i18next/i18next-parser/blob/master/docs/examples.md), I added these options to my config file:

```js
modulee.exports = {
  functions: ['t', '_', '__'],
  namespace: 'client',
  writeOld: false
}
```

However, I still get the same behavior. How do I catch `TAPi18n.__` calls with i18next-parser?

## Steps to reproduce

- Clone [this repository](https://github.com/ajsaraujo/Rocket.Chat)
- Run `i18next` to execute the parser

## My environment

- *runtime version*: node v14
- *i18next version*: 17.3.1
- *os*: Windows

**Comment by karellm** [comment]
Have you tried this:

```
modulee.exports = {
  functions: ['t', '_', 'TAPi18n.__'],
  namespace: 'client',
  writeOld: false
}
```

**Comment by ajsaraujo** [comment]
Just did. Unfortunately, I got the same results 😢
Do you have any other ideas on what might be going on?

**Comment by karellm** [comment]
Not really. Do you feel you can open a PR with a failing test case?

**Comment by ajsaraujo** [comment]
Of course. But I don't quite get it - what would I put in the PR? I mean, what I have right now is a repository I'm trying to parse, I didn't make any changes to `i18next-parser` itself.

**Comment by karellm** [comment]
Well you write a new test that demonstrate the failure to parse. We can't rely on an external repository to know if it is fixed or not. You can also write here a sample file and configuration that fails. I just don't have much time to debug your repository.

**Comment by karellm** [comment]
The `functions` option is a lexer configuration, not a global configuration. You can see an exemple in the README here: https://github.com/i18next/i18next-parser#javascript
