### ISSUE TITLE
Allow to disable separators

### ISSUE THREAD

**Issue by megapctr** [i18next/i18next-parser#35]
[You can use `false` to disable separators in 18next](http://i18next.com/translate/keyBasedFallback/#key-based-fallback). I think this library should behave the same way.

**Comment by megapctr** [comment]
Even better, it would be super nice if `i18next-parser` could read config from an i18next instance.

**Comment by karellm** [comment]
@megapctr I agree that matching i18next option is a good idea but that would be a non backward compatible change so I'm not sure it is worth it.

As to allowing to disable it and or read the config, I invite you to do a PR. I'm not sure how a build tool could read the config (unless there is a config file format I'm not aware of).

**Comment by karellm** [comment]
I'm really not sure what the use case is for this and can't find it in the docs anymore. If you still need this please describe the issue with greater details. I'm currently working on a rewrite, you can follow the status at #72. Closing this in the meantime.
