### ISSUE TITLE
Use the same option names as i18next does

### ISSUE THREAD

**Issue by megapctr** [i18next/i18next-parser#36]
I noticed a small difference between i18next and this library regarding the option names - i18next uses `nsSeparator`, whereas i18next-parser uses `namespaceSeparator`.

We should probably check other option names as well.

**Comment by karellm** [comment]
@megapctr Please consolidate similar requests together, this feels too close to #35 to justify 2 open issues.

**Comment by karellm** [comment]
I agree it would be better but since it would introduce an API change it would be non backward compatible. I don't think it is worth it. Closing for now
