### ISSUE TITLE
Parser convert unicode escape sequences in JSON

### ISSUE THREAD

**Issue by Elindorath** [i18next/i18next-parser#361]
## 🐛 Bug Report

This is very similar to #227, but using json output:

<img width="1233" alt="Capture d’écran 2021-06-22 à 12 16 28" src="https://user-images.githubusercontent.com/6784793/122907604-9d50da00-d353-11eb-92a8-afb452ec9828.png">

The `\u00a0` sequences are converted in utf8 (I guess?) when writing back the files.

## To Reproduce

In order to reproduce, just add `\u00a0` to any of your strings in a translation file and run the parser configured to output json files. This is a unicode escape sequence for a non-breaking space character.

## Expected behavior

The unicode escape sequences must stay intact after parser did its job.

## Your Environment

- *runtime version*: node v12
- *i18next version*: 20.3.2
- *os*: Mac

**Comment by karellm** [comment]
Fixed in `4.5.0`
