### ISSUE TITLE
React - handle `t` when used as a tagged template

### ISSUE THREAD

**Issue by kosciolek** [i18next/i18next-parser#376]
## 🚀 Feature Proposal

For React, support extraction when `t` is used as a tagged template (outside of being used as a normal function).

## Motivation

`t`, when used as a tagged template, offers a more concise syntax.

## Example

```tsx
const { t } = useTranslation();
<div>{t`Language`}<div>
```

**Comment by karellm** [comment]
You are welcome to open a PR with this feature!
