### ISSUE TITLE
Collect concatenated strings

### ISSUE THREAD

**Issue by megapctr** [i18next/i18next-parser#38]
i18next-parser doesnt collect concatenated strings, e.g. `i18n.t("Foo: " + "Bar")`. It would be awesome if it did.
[i18n-extract](https://github.com/oliviertassinari/i18n-extract/blob/master/index.js) does this, so maybe it won't be difficult to reimplement?

**Comment by megapctr** [comment]
I tried to port it and some of the tests pass, but most of them fail as babel raises syntax errors (e.g. invalid jsx). Also there's a problem with html and other templates, I'm not sure if babel can handle that

**Comment by karellm** [comment]
Do you actually need that? If so what is the use case?

**Comment by megapctr** [comment]
The use case is breaking very long strings into a few lines for readability

**Comment by megapctr** [comment]
Although I don't really need that, because I decided to go back to using i18n-extract, since the problem I had with it turned out to be a simple change. Sorry for making a mess here

**Comment by scags9876** [comment]
+1   We have the same issue... it would be great if i18next-parser could handle concatenated strings.

**Comment by karellm** [comment]
@scags9876 I'm maintaining this project for bugs but don't plan to add features to it. I will review a PR with documentation and test and publish a new version though.

**Comment by karellm** [comment]
I'm currently working on a big update for this project. This will be supported in `1.0`. You can follow the progress at #72 and see the [test case here](https://github.com/i18next/i18next-parser/pull/72/commits/6d7ee6c902cda3cc7de954298cccca5a4f63e996#diff-d52940a0daabaea11867b1531aa2e029R127)

I'm closing this issue, if you have question please have them on the PR regarding `1.0`
