### ISSUE TITLE
Allow umlauts in keys and values when exporting to json

### ISSUE THREAD

**Issue by Balfear** [i18next/i18next-parser#387]
## 🚀 Feature Proposal

I would like to be able to use special characters like German umlauts (ü, ä, ö, etc.) in my translation keys and values, either by default or via an optional config option.

## Motivation

Often when working on an application with translations, we want to just use the default plain text as the key. This is already supported by this library, but only when the default language is English. In an application with a default language like German, there will often be special characters like umlauts (ü, ä, ö, etc.) involved.

While this is currently not a problem when exporting translations to the yaml file format, there is additional transformation in place when exporting to json, which replaces these characters by it's ASCII equivalent and makes it very hard to work with.

The code that is causing this problem can be found on lines **298-301** of **/src/tranform.js**:

```
text = text.replace(
    /[\u007F-\uFFFF]/g,
    (chr) => `\\u${`0000${chr.charCodeAt(0).toString(16)}`.substr(-4)}`
)
```

## Example

Here you can see how the same translation key is handled when exporting to yaml versus json. What I would like to achieve is keeping the translation key and value as I write it in my application, the same ways it is exported to yaml (with the letter ü).

**/de/common.yml**
```
Dies ist ein übersetzter Text!: Dies ist ein übersetzter Text!
```

**/de/common.json**
```
"Dies ist ein \u00fcbersetzter Text!": "Dies ist ein \u00fcbersetzter Text!"
```

One way to do this without potentially breaking the original use of the additional transformation that is taking place in the json code path would be to introduse a new configuration option like **preserveUmlauts** or similar that either enhances the transformation code or just disables the transformation code on lines **298-301** of **/src/tranform.js**.

**Comment by karellm** [comment]
This is a mistake on my part, please follow #362. I will fix asap but in the meantime, stay on `4.2.0`. Not much as changed anyway.
