### ISSUE TITLE
Unexpected sort behavior between JSON keys at the same level

### ISSUE THREAD

**Issue by Elindorath** [i18next/i18next-parser#400]
## 🐛 Bug Report

Sorting is done on the full JSON path rather than directly on the keys of JSON objects. For example, the sort will compare "header.title" against "header_confirmation.title" (and other combinations) resulting on putting the `header` object after the `header_confirmation` one.

## To Reproduce

Given a code using 4 keys as:
```js
t('header.title');
t('header.label');
t('header_confirmation.title');
t('header_confirmation.label');
```

The produced catalog is:
```json
{
  "header_confirmation": {
    "title": "Another title",
    "label": "Another label"
  },
  "header": {
    "title": "A title",
    "label": "A label"
  }
}
```

## Expected behavior

The produced catalog should be:
```json
{
  "header": {
    "title": "A title",
    "label": "A label"
  },
  "header_confirmation": {
    "title": "Another title",
    "label": "Another label"
  }
}
```

## Your Environment

- *runtime version*: node v14
- *i18next version*: 17.0.16
- *os*: Mac
- *i18next-parser version*: 4.0.1

**Comment by karellm** [comment]
This is now fixed in `5.0.0` thanks to @Elindorath 's great work. Please read the [Changelog](https://github.com/i18next/i18next-parser/blob/master/docs/migration.md) and [migration guide](https://github.com/i18next/i18next-parser/blob/master/docs/migration.md) before updating.
