### ISSUE TITLE
Running i18next with `--silent` flag still produces output 

### ISSUE THREAD

**Issue by tommoor** [i18next/i18next-parser#417]
## 🐛 Bug Report

`i18next --silent` should produce no output, but it still outputs summary information.

### To Reproduce
![image](https://user-images.githubusercontent.com/380914/133353943-c67f3d29-eee4-4bfe-8e63-657fc5645c0a.png)

### Expected behavior

No console output

## Your Environment

- *runtime version*: 16.1.0
- *i18next version*: 20.6.1
- *os*: Mac

**Comment by karellm** [comment]
@tommoor You're right that from the README and name of the option, that's the behaviour I would expect. Could you make a PR? If not I should be able to get to it in couple days.

**Comment by karellm** [comment]
This is fixed in `4.7.0`
