### ISSUE TITLE
Interpolated value not included in extracted key when using react-i18next `t()` hook from a tsx file

### ISSUE THREAD

**Issue by kurt1288** [i18next/i18next-parser#429]
## 🐛 Bug Report

Interpolated value not included in extracted key when using react-i18next `t()` hook from a tsx file.

## To Reproduce

i18next.parser.config.js:

    module.exports = {
        createOldCatalogs: true,
        indentation: 3,
        keySeparator: false,
        useKeysAsDefaultValue: true,
        lexers: {
           js: ["JsxLexer"],
           ts: ["JsxLexer"],
           jsx: ["JsxLexer"],
           tsx: ["JsxLexer"],
           default: ["JsxLexer"],
        },
        locales: ["en", "fr"],
        input: ["src/**/*.{js,jsx,ts,tsx}"],
        output: "public/locales/$LOCALE/$NAMESPACE.json",
    };

In Page.tsx:

    import { useTranslation } from "react-i18next";

    const Page = () => {
        const { t } = useTranslation();

        return (
            <p>{ t("Test Date", { date: new Date() }) }</p>
        )
    }

## Expected behavior

Expected json output would be `"Test Date": "Test Date {{ date }}"`. Actual output I get is just `"Test Date": "Test Date"`

**Comment by karellm** [comment]
Can you point to the documentation of this in i18next? I don't see how this is a bug, at best it might be a missing feature.

**Comment by kurt1288** [comment]
@karellm, sorry but I'm not sure what you mean. It's just the basic interpolation of i18next (https://www.i18next.com/translation-function/interpolation). I searched the issues here and found related, but older, issues regarding strings with interpolated values extraction (see https://github.com/i18next/i18next-parser/issues/88 and https://github.com/i18next/i18next-parser/issues/152).

Maybe my understanding of the current expected behavior is incorrect? Given the following:

`t("My name is", { name: "Bob" })`

I assumed, from previous issues here and from the examples that i18next shows, that the output would be:

    {
       "My name is": "My name is {{ name }}"
    }

Is that not a correct assumption?

**Comment by karellm** [comment]
How do you want this code parser to know where to put the variable? Imagine the following example:

```
t('is a beautiful name`, {name: "Bob"}
```

I bet you wouldn't be expecting `is a beautiful name {name}` as a default value but `{name} is a beautiful name`. The parser is not smart enough to understand this kind of subtleties and never will.

Nothing in the documentation let me see that we need to generate a default value based on the key and variable name. This job is on you to do.

**Comment by Kolby-Udacity** [comment]
It would be nice if could make it clear that a translation includes a variable. It would help the translators knowing they have a variable available to use.

I agree that there isn't much you can do without more context, but one solution that comes to mind is making `defaultValue` type `string` | `(variableNames: string[]) => string`, and proving the variable names which we can then insert into our default value as we see fit.

Usage would look something like:

```
defaultValue: (variablesNames) => {
    return `__MISSING__variables:${variablesNames.join(',')}`
},
```

With an output of:
`'__MISSING__variables:firstName,lastName'`
