### ISSUE TITLE
Feature Request: Ability to version translation files

### ISSUE THREAD

**Issue by amandapouget** [i18next/i18next-parser#430]
- Is this a bug or a feature request? Feature Request
- What version are you running (`0.x` or `1.x`)?  Latest
- Which runner (cli, gulp...)? Cli

## What I'm trying to do?

I'd like a way to add a version number to the file. The purpose is for coordination with human translators. It would be nice if this value were NOT erased as an "old, used string" when running the parser.

## How am I doing it?

{
  _metadata: { version: 123 }
}

## What was the result?

Currently all unused strings are clobbered away with no way to indicate an exception.

## What was I expecting?

Some way to version these files to make a useable workflow.

**Comment by karellm** [comment]
@amandapouget Is there a reason you don't use Git?

**Comment by amandapouget** [comment]
Version control only works for developers.

When you have to send translation files to a third party translation service, get them back and then commit them to a codebase, it helps from a logistics point of view to be able to talk to the translators with a way to label the files.

**Comment by karellm** [comment]
If the translators are non technical, why not use a tool like this: https://locize.com/ ?

**Comment by amandapouget** [comment]
It feels very constraining if the _only_ way to version a file atomically is to sign up for an ongoing, paid service.

**Comment by amandapouget** [comment]
It wouldn't be technically very hard to simply skip a key. e.g. "skipKeys: [array]" and then where the overwrite code is... just skip those.

I would think there would be a lot more use cases than just the one I've identified. For example, if a person wanted to mark a particular translation file as having been through certain QA processes, approved by a particular person, etc.

This is the way most document control happens in the corporate world. Right on the doc you see version number.

**Comment by karellm** [comment]
I'm trying to think of a workaround, why don't you add `t('_metadata.key')` in your code? That way the key will not disappear. 

I understand your request but I believe this requires a lot more planning than just adding a `_metadata` object to the catalog and I don't have the expertise to draft a proposal for proper versioning in big teams.
