### ISSUE TITLE
Ability to use `null` as default value

### ISSUE THREAD

**Issue by viktorstrate** [i18next/i18next-parser#431]
## 🚀 Feature Proposal

Add an option to set the default value to `null` rather than an empty string (`""`).
I tried setting the `defaultValue` property to `null`, but then the key was simply ignored.

## Motivation

My setup interprets the empty string as a translation and thus shows no text on the UI for that key, but it uses a fallback if the key is `null`

## Example

Instead of outputting:

```json
{
  "key": ""
}
```

for empty keys, return:

```json
{
  "key": null
}
```

**Comment by karellm** [comment]
@viktorstrate I'm very reluctant to default to `null` instead of `""` in the catalog since it will make the job of filling the translations a lot more painful. 

Is there a reason you don't change your setup to ignore empty strings?

**Comment by viktorstrate** [comment]
@karellm that's a good point, I migrated from [babel-plugin-i18next-extract](https://github.com/gilbsgilbs/babel-plugin-i18next-extract) which used `null` as the default.
But I guess it's a little cleaner to use `""` especially for translators who aren't familiar with JSON.

I didn't mean this to be the default, but simply to have the option to use `null`.

**Comment by karellm** [comment]
I'm very cautious when adding options as I don't want to overcomplicate things. This isn't solving an actual problem so I won't add this option. I invite you to change your implementation to ignore the empty strings.

**Comment by viktorstrate** [comment]
I acknowledge that, I will update my project to use empty strings. 👍
