### ISSUE TITLE
Unnecessary empty lines when using plurals

### ISSUE THREAD

**Issue by aberonni** [i18next/i18next-parser#439]
## 🐛 Bug Report

When using plurals, the parser outputs unnecessary extra empty lines. I think this is due to changes in [i18next v21.0.0](https://github.com/i18next/i18next/releases/tag/v21.0.0)

## To Reproduce

Example repo: https://github.com/aberonni/i18next-parser-plural-bug-example

After running `yarn i18n:extract` on the above repo, you will see the following on `git diff`:

```diff
diff --git a/src/locales/en/general.json b/src/locales/en/general.json
index d8b2fec..19afca9 100644
--- a/src/locales/en/general.json
+++ b/src/locales/en/general.json
@@ -1,5 +1,7 @@
 {
   "button": "Click me",
+  "description": "",
+  "description_plural": "",
   "description_one": "You've clicked me {{count}} time",
   "description_other": "You've clicked me {{count}} times"
 }
```

## Expected behavior

No changes to the locale files.

## Your Environment

- *runtime version*: node v14.16.1
- *i18next version*: 21.2.0
- *os*: Mac

**Comment by karellm** [comment]
Support for i18next 21 is now part of `5.0.0` thanks to @Elindorath 's great work. Please read the [Changelog](https://github.com/i18next/i18next-parser/blob/master/docs/migration.md) and [migration guide](https://github.com/i18next/i18next-parser/blob/master/docs/migration.md) before updating.

If you still have issues after that, feel free to reopen this issue.

**Comment by aberonni** [comment]
That did indeed fix it. Thanks!
