### ISSUE TITLE
Scan data-i18n-options in HTML

### ISSUE THREAD

**Issue by duanbw** [i18next/i18next-parser#45]
When data-i18n and data-i18n-options coexist in a DOM only data-i18n is recognized, suppose I wanted a translation with context, I couldn't get it with this tool

**Comment by karellm** [comment]
Can you detail the issue a little bit more? Or even better, provide a failing test?

**Comment by karellm** [comment]
Closing this by lack of activity. It will be included in the rewrite. To track progress, look at #72
