### ISSUE TITLE
Parse typescript generic type information when generating the key

### ISSUE THREAD

**Issue by AzariasB** [i18next/i18next-parser#454]
## 🚀 Feature Proposal

When, in a typescript file, the lexer encounters the following : 
```typescript
// The function 'TR' just returns the given parameter
const key = TR<{count : number}>('namespace:my.key');

const actualTranslation  = i18next.t(key, {count: 1});
```

Currently, it generates the following : 
```json
{
 "my": {"key" :""}
}
```

The proposal is to improve the lexer, so that it would generate the key for both singular and plural (my.key_one, my.key_other) by parsing the information from the generic type. (By enabling an option or something like that)

## Motivation

To ensure that the parameters passed to the translator, all my keys are declared this way. 
The parser currently does not generates the correct keys (only my.key), since when the key is used, it's a variable, and not a string literal.

## Example

With the template parsing, it would generate the following

```json
{
 "my": {
   "key_one": "",
   "key_other": ""
 }
}
```

I'm aware that this is actually very specific. I was first thinking of just forking the project and implementing this just for me. But I wanted to know if maybe that could be an interesting feature to directly add to this project ?

**Comment by karellm** [comment]
To make a short answer, it is difficult to know which plural form we should generate but it is feasible. The challenge is that it will change for every locale. If you are willing to add an option `generatePluralKeys` I believe it would be a welcome addition though. I would suggest you write a small proposal for what the option would do and then open a PR.

**Comment by AzariasB** [comment]
After poking a bit, I realized that even adding this feature would not be enough for what I need.
So I'll just close this
