### ISSUE TITLE
T function calls with inline comments are not added to output

### ISSUE THREAD

**Issue by jcksonhe** [i18next/i18next-parser#490]
- Is this a bug or a feature request?
Feature request
- What version are you running (`0.x` or `1.x`)?
5.3.0
- Which runner (cli, gulp...)?
CLI

## What I'm trying to do?

I want to add inline comments into T function calls. For example:
`t("key" /* some comment */, "my string", options)`

However, the parse fails to detect the T function call in this scenario. I was expecting to get `key: "my string"` in the output, but nothing for the key was added 😢 

## How am I doing it?

Here is my config file:

```
{
    sort: true,
    createOldCatalogs: false, 
    locales: ["en"],
};
```

## What was the result?

All key/string pairs were added into the output except for the T function calls with inline comments.

## What was I expecting?

T function calls with inline comments to be parsed and added into the output as well.

**Comment by jcksonhe** [comment]
Closed because it can be fixed by modifying the lexers.

**Comment by karellm** [comment]
@jcksonhe Can you share your solution or create a PR? I believe this would be a welcome addition.
