### ISSUE TITLE
ES Module support in parser.config.js

### ISSUE THREAD

**Issue by mquandalle** [i18next/i18next-parser#497]
Hello,

I have an app where all the config files have been migrated to ES Modules. However `i18next-paser` is the only dependency that can't import a `parser.config.js` written with the ESM syntax.

## 🐛 Bug Report

```
/home/mquandalle/project/node_modules/i18next-parser/bin/cli.js:32
  config = require(path.resolve(program.opts().config))
           ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /home/mquandalle/project/site/scripts/i18n/parser.config.js from /home/mquandalle/project/node_modules/i18next-parser/bin/cli.js not supported.
Instead change the require of parser.config.js in /home/mquandalle/project/node_modules/i18next-parser/bin/cli.js to a dynamic import() which is available in all CommonJS modules.
```

Originate from:

https://github.com/i18next/i18next-parser/blob/054e29a7b0cae3860857cb0cd5b0d5eac2dd1d0a/bin/cli.js#L33

## To Reproduce

Use a `parser.config.mjs` with the `--config` argument, or keep the default `.js` but use `type: module` in the nearest `package.json`.

## Your Environment

- *runtime version*: node v16.11
- *i18next-parser version*: 5.3.0
- *os*: Linux

**Comment by mquandalle** [comment]
Should be fixed by #508.

**Comment by karellm** [comment]
@mquandalle You are right that v6 is supposed to fix this. I just have one bug that I haven't got around to solve yet.

**Comment by Toilal** [comment]
For users migrating their project to ESM (using `type: module` in package.json), you have to rename your configuration file for it to have the `.cjs` extension, and specify the filename using the `-c` command line flag

```
yarn i18next -c i18next-parser.config.cjs
```

**Comment by karellm** [comment]
I just publish `6.0.0`
