### ISSUE TITLE
in jade file attributes preceded with ( are not matched

### ISSUE THREAD

**Issue by arjanvanderleden** [i18next/i18next-parser#50]
For example:

`.my-title(t="home.title")` is not matched by attribute regex on line 144 of index.js
`var attributeWithValueRegex = new RegExp( '(?:\\s+' + attributes + '=")([^"]*)(?:")', 'gi' );`
the regex requires a preceding space (as is always the case in html)

suggested fix: 
instead of space class `\s` use non-word class `\W`
`var attributeWithValueRegex = new RegExp( '(?:\\W+' + attributes + '=")([^"]*)(?:")', 'gi' );`

**Comment by karellm** [comment]
@arjanvanderleden Can you please make a PR with a test to cover this example? I will review and publish a new version but I don't really spend time actually coding this project anymore. Thanks!

**Comment by birdy-** [comment]
I think I fixed this with https://github.com/i18next/i18next-parser/pull/52
Can you check it ?

**Comment by arjanvanderleden** [comment]
I closed pull request #51 which also fixed the issue
Regards Arjan

**Comment by karellm** [comment]
Should be fixed in `0.10.1`
