### ISSUE TITLE
cannot parse the keys from all my specified project files

### ISSUE THREAD

**Issue by buyhighHippo** [i18next/i18next-parser#502]
## 🐛 Bug Report

Can not manage to retrieve all my keys and write them in my output files, it is currently missing every keys called in my components/**/*.{ts,tsx}, the other keys are well retrieved as wanted

## To Reproduce

my config file is set with input as below
```js
// Paste your code here
input: "./!(node_modules)/**/*.{ts,tsx}",
```

## Expected behavior

parse all my specified files and add the new found keys in my output: "public/locales/$LOCALE/$NAMESPACE.json" file.

## Your Environment

- *runtime version*: node v14.17.4
- *i18next version*: 5.3.0
- *os*: Windows 10

**Comment by tradingstratagem** [comment]
I have a similar problem, after updating to version 5.x.x it doesn't extract translation correctly

**Comment by joepsyko** [comment]
I have a similar problem, after updating to version 5.x.x it doesn't extract translation correctly

**Comment by karellm** [comment]
@buyhighHippo  Can you provide a reproduceable example?

**Comment by glekner** [comment]
@karellm we have the same issue in our repo https://github.com/kubevirt-ui/kubevirt-plugin
if you check https://github.com/kubevirt-ui/kubevirt-plugin/blob/main/locales/en/plugin__kubevirt-plugin.json
you will see only 216 keys, for some reason the parser does not parse files inside `src/utils/**`

can you please help?

**Comment by tradingstratagem** [comment]
I found the problem, I had this in my source code:
`label: t(''),`
After removing it, the parser works perfectly

**Comment by upalatucci** [comment]
I can confirm! Also in our repo https://github.com/kubevirt-ui/kubevirt-plugin

**Comment by alk-mandrianarijaona** [comment]
I have just checked our project, I also found a `t('')`, this must be the root cause. I will remove that. Thanks @tradingstratagem @upalatucci

**Comment by alk-sdavid** [comment]
Hi 👋 indeed empty keys are resetting the namespace catalog here: https://github.com/i18next/i18next-parser/blob/master/src/helpers.js#L31 I'm not sure to understand the logic here 🤔 Is it really intended?
`t('')` can mess up all translations from a project, and there is another use case I found in our codebase:

```js
i18n.t("some key: {{key}}", { key: someVar })
```

It extracts an empty key too. After removing all the empty keys, it seems to work just fine, but this behavior looks quite dangerous 😅 what do you think?

**Comment by karellm** [comment]
Thanks for finding the issue @alk-sdavid. I've pushed a patch as `6.4.0`

**Comment by alk-sdavid** [comment]
thanks @karellm it seems to work as expected now 👍
