### ISSUE TITLE
`--fail-on-update` unknown option for 4.x.x version that support i18next JSON v3 

### ISSUE THREAD

**Issue by davydspotnana** [i18next/i18next-parser#507]
## 🐛 Bug Report

Please cherrypick this PR https://github.com/i18next/i18next-parser/pull/471/files for `4.x.x` version and released it!

as we have a huge code base and don't have enough time to migrate to a new format  i18next JSON v4( 

## To Reproduce

```
yarn global add i18next-parser@4

i18next --fail-on-update
error: unknown option '--fail-on-update'
```

## Expected behavior

work properly 

## Your Environment

- *runtime version*: node 16
- *i18next version*:  19.5.3
- *os*:  Linux

**Comment by karellm** [comment]
I don't maintain older version. If you want support with that, you can hire me to do it. You can contact me privately via my profile.

**Comment by davydspotnana** [comment]
@karellm I can create PR for the older version? Do you release it for 4.x.x tag?
