### ISSUE TITLE
dynamically computed namespaces are parsed as the variable name

### ISSUE THREAD

**Issue by chiptus** [i18next/i18next-parser#509]
## 🐛 Bug Report

When calculating the namespace dynamically (for example, if I want to use the same namespace for all Trans components), i18n-parser uses the namespace variable name as the namespace.

## To Reproduce

```ts
const translationNS = 'my-own-ns'
const {t} = useTranslation(translationNS);

return (
  <div>
    <Trans ns={translationNS}>something</Trans>
   {t('more')}
  </div>
```

## Expected behavior

I expect to have a new json file names `my-own-ns.json` with the following:

```
{
   something: 'something',
   more: 'more'
}
```

## Your Environment

- *runtime version*: node v16
- *i18next version*: 21.3.3
- *os*: Linux

**Comment by karellm** [comment]
The parser does not run or interpret your code. If you don't use a string literral it will not work. That said it should throw a warning and not grab the variable name.

**Comment by karellm** [comment]
I double checked and it ignores the namespace if it is a variable so I'm closing this.
