### ISSUE TITLE
Different numbers of plurals in polish between json v3 and json v4

### ISSUE THREAD

**Issue by maciejregula** [i18next/i18next-parser#510]
Hello,

When I extract translations in json v3 I have following types of plurals in polish language:
```json
{
    "Send {{count}} invitation(s)_0": "",
    "Send {{count}} invitation(s)_1": "",
    "Send {{count}} invitation(s)_2": ""
}
```
When I do the same but with option to extract in json v4
```js
i18nextOptions: {
    compatibilityJSON: "v4"
}
```

I have following result:

```json
{
    "Send {{count}} invitation(s)_one": "",
    "Send {{count}} invitation(s)_few": "",
    "Send {{count}} invitation(s)_many": "",
    "Send {{count}} invitation(s)_other": ""
}
```

According to this tool https://jsfiddle.net/6bpxsgd4, there are 3 forms of plurals in polish, so why 4 suffixes are generated in JSON v4?

"i18next-parser": "^5.4.0"
"i18next": "^21.5.2"

**Comment by jamuhl** [comment]
<img width="450" alt="image" src="https://user-images.githubusercontent.com/977772/153168012-9185bfa4-767f-4b07-ad7d-6befbacb3056.png">

there are four

**Comment by jamuhl** [comment]
v3 vs v4 -> v3 used not cldr as source ---> cldr uses the "other" form for decimals - which was not supported in v3

**Comment by maciejregula** [comment]
Thank you for your clarification. Ok, so the issue is in i18next-conv. Because when I convert the json in v4 format to the gettext, it produces only 3 suffixes:
msgstr[0]
msgstr[1]
msgstr[2]

Probably gettext doesn't support decimals.

**Comment by jamuhl** [comment]
gettext come with own pluralrules as far i know - which are not based on cldr (but closer to v3 of i18next)
