### ISSUE TITLE
Entity encoding is not recognized by the lexer

### ISSUE THREAD

**Issue by myl7** [i18next/i18next-parser#530]
## 🐛 Bug Report

When using entity encoding in JSX like `&apos;`, i18next-parser can not recognize it and convert it to `'` in the extracted keys, causing `<Trans>` without i18nKey can not select the translated value.

## To Reproduce

A minimal reproducible example is available on [myl7/i18next-parser-mwe](https://github.com/myl7/i18next-parser-mwe)

## Expected behavior

`<Trans>I&apos;m myl7!</Trans>` should be extracted as the key `I'm myl7!` other than literally `I&apos;m myl7!`

## Your Environment

- `node -v`: v17.7.2
- `i18next --version`: 6.0.0
- os: Linux

**Comment by nicegamer7** [comment]
Fixed by #892.

**Comment by karellm** [comment]
Should be fixed as of `8.7.0`
