### ISSUE TITLE
Some nice to have features

### ISSUE THREAD

**Issue by balazserdos** [i18next/i18next-parser#58]
I'm using your tools to automatize the translation process. Like to say thank you at first.
I'd like to share some nice to have features for the future.

- Write result to the STDOUT
- If you write to the hard drive, could force the file creation even if there is no key in the file. (empty json)

Hope it was helpful.

**Comment by karellm** [comment]
@balazserdos Thanks for sharing. You are welcome to make a PR with these changes if they are important to you!

**Comment by karellm** [comment]
Closing by lack of activity. Please open one ticket per feature request if you still want this and detail what is the use case (especially for stdout).
