### ISSUE TITLE
Context is not detected when not on the same line as translation key

### ISSUE THREAD

**Issue by tkrugg** [i18next/i18next-parser#59]
In this case, key goes undetected.

```js
i18n.t('date: {{date}}', 
    {date: date},
    {context: 'notifications'}
);
```

**Comment by birdy-** [comment]
Is your `{date: date}` works ? I think the regexp read only one line, so it's not related to context parsing but general parsing limited to one line.

**Comment by karellm** [comment]
I'm currently working on a big update for this project. This will be supported in 1.0. You can follow the progress at #72 and see the [test case here](https://github.com/i18next/i18next-parser/pull/72/commits/6d7ee6c902cda3cc7de954298cccca5a4f63e996#diff-d52940a0daabaea11867b1531aa2e029R53)

I'm closing this issue, if you have question please have them on the PR regarding 1.0
