### ISSUE TITLE
More options for tweaking file names

### ISSUE THREAD

**Issue by rijk** [i18next/i18next-parser#60]
For another i18n library I'm trying to use in combination with this (awesome) scanner, it's required the JSON files are in a structure like `i18n/en.i18n.json`. However, it seems besides the folder the files are placed I have no ability to tweak the file naming of the generated JSON files. I have browsed through the source, but cannot find if/how to do this. Is this possible, and if not, could it be made possible you think?

**Comment by rijk** [comment]
Looking through [the code](https://github.com/i18next/i18next-parser/blob/master/test/parser.js#L174-L176), I found two options that would enable this I think: `prefix` and `extension`. Would it be possible to add these to the CLI options?

**Comment by karellm** [comment]
@rijk If you make the PR I will review it. I will get to improve this project soon but can't commit to any deadline.

**Comment by karellm** [comment]
This is now in `0.12.0`.
