### ISSUE TITLE
Support TypeScript type casts in JSX

### ISSUE THREAD

**Issue by joshkel** [i18next/i18next-parser#603]
## 🚀 Feature Proposal

i18next-parser cannot currently handle TypeScript `as` casts within a JSX file. For example:

```tsx
<Trans>
  Hello, <strong>{{name} as any}</strong>!
</Trans>
```

gets extracted as `"Hello, <1>{{ name } as any}</1>!"` instead of `"Hello, <1>{{name}}</1>!"`.

## Motivation

As discussed in https://github.com/i18next/react-i18next/issues/1483, React 18's type definitions cause TypeScript to start throwing errors for code such as

```tsx
<Trans>
  Hello, <strong>{{name}}</strong>!
</Trans>
```

since a `{ name }` object is not a valid React child. react-i18next offers a new `allowObjectInHTMLChildren` option to adjust TypeScript's type definitions to allow this; however, it's a fairly drastic option and causes all React children everywhere to allow arbitrary objects (even if they're not part of `<Trans>`).

An alternative is to use an `as any` cast (or similar) at the call site:

```tsx
<Trans>
  Hello, <strong>{{name} as any}</strong>!
</Trans>
```

However, i18next-parser doesn't currently parse this properly.

## Example

See above.

**Comment by karellm** [comment]
Deployed as part of 6.6.0
