### ISSUE TITLE
yaml output?

### ISSUE THREAD

**Issue by bonesoul** [i18next/i18next-parser#61]
i'm using https://github.com/i18next/i18next-node-fs-backend with yaml files, is it possible for i18next-parser to output yaml files too instead for json?

**Comment by karellm** [comment]
@bonesoul It is possible but if you want it soon, you should make a PR for it.

**Comment by karellm** [comment]
This is addressed in #72. In `1.x`, set `extension` to `.yml` to get a yml output.
