### ISSUE TITLE
Keys as content

### ISSUE THREAD

**Issue by viktorstrate** [i18next/i18next-parser#64]
I'm using i18next with React ([react-i18next](https://react.i18next.com/)), and this parser is working fine, except that the i18next keys are the same as the content. Like [this example](https://www.webpackbin.com/bins/-KoCD3kvA-4QJNaHpkxi).

Right now, when I run the parser, the new keys stores empty values in the JSON files, as default and I have to copy / paste the key to the value. Is there any way to set the value to the same as the key?

Another nice feature, would be to set a default value, so it's easier to see what hasn't been translated yet

#### Currently
```JSON
{
  "Hello world, this is some text": "",
  "Another internationalized string": ""
}
```

#### Expected
```JSON
{
  "Hello world, this is some text": "Hello world, this is some text",
  "Another internationalized string": "Another internationalized string"
}
```

#### Default Value
```JSON
{
  "Hello world, this is some text": "__UNTRANSLATED_VALUE__",
  "Another internationalized string": "__UNTRANSLATED_VALUE__"
}
```

**Comment by karellm** [comment]
This will be added to #72. Track changes there, closing this for now.

**Comment by tfaieta** [comment]
Hey! Thanks for this great library! I just wanted to ask if this feature was ever implemented?

**Comment by karellm** [comment]
It looks like it fell into the cracks, I'll try to have a look this weekend.

**Comment by tfaieta** [comment]
You think it’d be very hard to implement? I definitely have some time this weekend and am interested in helping out with this feature!

**Comment by karellm** [comment]
I believe it's gonna be very easy to do, a good project for a first contribution to the project. Feel free to open a PR! If you have doubts about the implementation, you can open a WIP PR too and we can move the conversation there. My only request is that you add proper documentation and tests. Thanks!

**Comment by tfaieta** [comment]
Sounds good! Hope to have that PR up soon 👍

**Comment by karellm** [comment]
Added to `1.0.0-beta34`
