### ISSUE TITLE
Add a config to keep some dynamic keys

### ISSUE THREAD

**Issue by pcorpet** [i18next/i18next-parser#693]
## 🚀 Feature Proposal

Add an option so that `i18next-parser` keeps some of the keys that are in the translation files but are not extracted from the code.

## Motivation

When using dynamic keys or dynamic contexts, there are multiple reasons for adding some keys that would be used at runtime while not easy to extract from the code statically. I'd like to be able to use `i18next-parser` to get all the other keys right, but trust me on the keys that I've added myself to the translation files.

As of v7, I only have the choice to either keep all existing translations (`keepRemoved` option) or delete all the ones that `i18next-parser` cannot extract from the code. I'd like to have another option and list patterns for which I want to keep the translations that exist.

## Example

Given the following code (using React):
```tsx
  const {t} = useTranslation()
  return <p>
    {t('pickACountryQuestion')}
    <select>
     {countries.map(countryId => <option value={countryId}>{t(`countryName.${countryId}`)}</option>)}
    </select>
  </p>
```

Adding this in the `i18next-parser.config.js`:
```js
module.exports = {
  keepRemovedPatterns: [
    /^translation:countryName\.\w+/,
  ]
}
```

I'd like to keep all the `countryName` sub tree containing something like:
```json
  "countryName": {

    "BDI": "Burundi",
    "BEL": "Belgium",
    "BEN": "Benin",

  }
```
while still removing other keys not used in my code.

**Comment by pcorpet** [comment]
I'm happy to send a PR, if I get a nod that it would be welcome.

**Comment by karellm** [comment]
@pcorpet There is another option that is to add a comment in the code with the possible values. That way the keys wouldn't be removed. Have you considered that solution?

**Comment by pcorpet** [comment]
I have considered it, but don't want to add *all* the keys that could exist as comments in my code.

**Comment by karellm** [comment]
Makes sense, feel free to make a PR and I'll review it.
