### ISSUE TITLE
[7.0.3] TS file is missing in the build

### ISSUE THREAD

**Issue by gynekolog** [i18next/i18next-parser#694]
## 🐛 Bug Report

The current build is missing typescript definitions.

`Cannot find module 'i18next-parser' or its corresponding type declarations.`

## To Reproduce

https://codesandbox.io/s/i18next-parser-missing-ts-reproduction-2nkws7?file=/i18next-parser.config.ts

## Your Environment

- *runtime version*: node v16
- *i18next version*: 7.0.3
- *os*: Mac

**Comment by karellm** [comment]
This is in `7.5.0`
