### ISSUE TITLE
Config file does not exist: i18next-parser.config.js

### ISSUE THREAD

**Issue by denvradiy** [i18next/i18next-parser#721]
## 🐛 Bug Report

i18next --config i18next-parser.config.js not working.

I've created i18next-parser.config.js in the root of my project and trying to run it but always getting this error:
<img width="856" alt="Screenshot 2022-12-09 at 17 29 19" src="https://user-images.githubusercontent.com/49561056/206736406-3250a9e6-b366-44cc-a588-b0bb07fc2318.png">

## Expected behavior

Expected successfully extracted keys

## Your Environment

- *runtime version*: node v14
- "next-i18next": "^12.1.0",
- *os*: Mac

**Comment by karellm** [comment]
What is your file structure of the project and what is the output of the `pwd` command in the terminal?

**Comment by denvradiy** [comment]
@karellm Hi! Thank you for quick response ! 

I don't know how I fixed this error but it started working somehow. Not sure what I changed. Tried to change the path to the config and then reverted all the changes 🙂

I think it can be closed for now. 

If something is wrong again I'll create a MRE repo and open a new issue.
