### ISSUE TITLE
Do not sort keys

### ISSUE THREAD

**Issue by tkrotoff** [i18next/i18next-parser#74]
Keys are currently sorted alphabetically `translation.json`:
```JSON
{
  "A": "a",
  "B": "b",
  "C": "c"
}
```

Would be nice to have the keys without order, as they appear inside the source code (e.g. in the order  they are parsed):
```JSON
{
  "C": "c",
  "A": "a",
  "B": "b"
}
```

This way the keys follow the source code logic.

I even believe the "source code order" should be the default one and a `--alphabetical-order` option should be added.

**Comment by karellm** [comment]
Noted, I've added this to the `1.0.0` roadmap. Should land in beta this week. You can track the progress at #72

If you need it promptly in `0.x` I invite you to make a PR.

**Comment by tkrotoff** [comment]
Sort is done here: https://github.com/i18next/i18next-parser/blob/0dd40a99942035e42a6f1ad14a721ed5a9e0ca7f/index.js#L211

Can be replaced by: `self.translations = _.uniqBy( self.translations, getKey )`

**Comment by karellm** [comment]
I know but it would need to be an option to preserve backward compatibility. It is a wanted feature for many, so I won't just remove it. I'm ok making it optional though in `0.x`.

In `1.x`, it will be opt in. But `1.x` will have many breaking changes.

**Comment by karellm** [comment]
This is addressed in `1.x`. You can track progress at #72. Closing this for now as I won't add it as part of `0.x`.

**Comment by pasisavolainen** [comment]
I think this was a bad call, this introduces useless churn as code gets refactored and moved around.
Code order is mostly meaningless.

**Comment by karellm** [comment]
Then set `sort: true`. Am I missing something ?

**Comment by pasisavolainen** [comment]
No, I was blind and didn't see it. I do still argue it's a bad default (at least as per. README.md)

**Comment by scottgigante-hubflow** [comment]
Coming back here three years later to say it's still a bad default.
