### ISSUE TITLE
TypeError parsing TypeScript code

### ISSUE THREAD

**Issue by danielrentz** [i18next/i18next-parser#764]
## 🐛 Bug Report

Parsing TypeScript code raises a type error when using `TFunction` without type parameters.

Introduced with https://github.com/i18next/i18next-parser/commit/1547997e522579dbcea155d96f8fe8ea3baf2f3a

## To Reproduce

Minimum code example:
```ts
import type { TFunction } from "i18next";
function test(t: TFunction): void { }
```
raises
```
TypeError: Cannot read properties of undefined (reading 'length')
    at JavascriptLexer.functionParamExtractor (node_modules/i18next-parser/dist/lexers/javascript-lexer.js:127:23)
    at parseTree (node_modules/i18next-parser/dist/lexers/javascript-lexer.js:81:41)
    at visitNodes (node_modules/typescript/lib/typescript.js)
```

The following code passes without error:
```ts
import type { TFunction } from "i18next";
function test(t: TFunction<"translation">): void { }
```

Apparently, `node.type.typeArguments` becomes `undefined` if the type does not contain any arguments. This will not be checked in function `functionParamExtractor` (line 127). There is another place in this file that performs this check though (function `expressionExtractor`, line 228).

## Expected behavior

Parser does not exit.

## Your Environment

- *runtime version*: node v18
- *i18next version*: 22.4.9
- *typescript version*: 4.9.4
- *os*: Windows,

## Patch

I will prepare a PR.

**Comment by sibelius** [comment]
it is working great, thanks
