### ISSUE TITLE
On cli usage -l de extracts to folder fr on 1.0.0 beta2

### ISSUE THREAD

**Issue by razielidog** [i18next/i18next-parser#79]
Hello there, i have this problem i am using the cli with this command: 
i18next "src/**/*.js" -o . -l en,de
and i get ./locales/en and ./locales/fr
Is there an issue with the german language or am i doing something wrong
Thank you

**Comment by karellm** [comment]
Which version `i18next version` are you running?

Please note that `1.0.0-beta` is now published under the `next` tag on npm. If you are using that version, please read the documentation. the `-l` option was deprecated in favour of a config file.

**Comment by razielidog** [comment]
I followed your advice to make a config file and it works as expected.
Thank you for the quick reply.
