### ISSUE TITLE
Publish 8.1.0 to npm

### ISSUE THREAD

**Issue by threema-danilo** [i18next/i18next-parser#846]
## 🐛 Bug Report

Version 8.1.0 was bumped in the GitHub repo, but neither tagged nor published to npmjs.org.

It would be fantastic if you could publish it, since it adds support for TypeScript 5.x. Thank you in advance for your maintenance work!

## To Reproduce

    npm install i18next-parser@~8.1.0

**Comment by karellm** [comment]
`8.2.0` was just published

**Comment by threema-danilo** [comment]
@karellm thank you!
