### ISSUE TITLE
weird behavior when the output option is set

### ISSUE THREAD

**Issue by jare-talend** [i18next/i18next-parser#87]
- Is this a bug or a feature request? bug
- What version are you running (`0.x` or `1.x`)? 1.0.0-beta10
- Which runner (cli, gulp...)?cli

## What I'm trying to do?

run cli with the output option

## How am I doing it?

i18n.json
```
{
  "output": "src/"
}
```

The command I'm running:

```
i18next src/**/*.js  -c i18n.json
```

## What was the result?

i18nTransform get the existing catalog from **src/en/namespace.json** and write the transform catalog in 
**src/src/en/namespace.json**

## What was I expecting?

I was expecting that i18next-parser write my file in **src/en/namespace.json** instead of **src/src/en/namespace.json**

**Comment by karellm** [comment]
I will be afk this weekend, if it is blocking I invite you to make a PR. Otherwise I will look at it next week.

**Comment by karellm** [comment]
I just published `1.0.0-beta11` that should fix this. Thanks for the bug report!
