### ISSUE TITLE
Changes in order should cause --fail-on-update to fail

### ISSUE THREAD

**Issue by mspiess** [i18next/i18next-parser#926]
## 🐛 Bug Report

When the keys are complete but in a wrong order calling `i18next --fail-on-update` with `sort: true` in the config does update the files but not fail.

## To Reproduce

1. Have a project with an unsorted translation file and `sort: true` in the config.
2. Run `i18next --fail-on-update 'src/**/*.{ts,tsx,js,jsx}'`

## Expected behavior

Expected the command to fail, since there are updates in the translation file.

## Your Environment

- *runtime version*: node v20
- *i18next-parser version*: 8.3.0
- *os*: Windows

**Comment by karellm** [comment]
@mspiess It makes sense. Can you make a PR?

**Comment by mspiess** [comment]
Yes, I will try to make time on the weekend. Is this a breaking change?

**Comment by karellm** [comment]
I don't think it is no.

**Comment by karellm** [comment]
Deployed as `8.11.0`
