### ISSUE TITLE
Error while following the documentation

### ISSUE THREAD

**Issue by alexis-exaud** [i18next/i18next-parser#929]
## Documentation issue

I'm getting this error: `Module '"i18next-parser"' has no exported member 'gulp'.`

From this code that is literally copy-pasted from the documentation:

```javascript
import { gulp as i18nextParser } from 'i18next-parser'

gulp.task('i18next', function () {
  gulp
    .src('app/**')
    .pipe(
      new i18nextParser({
        locales: ['en', 'de'],
        output: 'locales/$LOCALE/$NAMESPACE.json',
      })
    )
    .pipe(gulp.dest('./'))
})
``` 

Also, in `gulp.task()` and `gulp.src()`, `gulp` is undefined.
## Motivation

I can't use the package if the documentation for the setup is wrong and/or lacking key info...

**Comment by DavidArutiunian** [comment]
@alexis-exaud have you find a way to import parsers?
