### ISSUE TITLE
key is a variable, can not be parsed?

### ISSUE THREAD

**Issue by codedaybyday** [i18next/i18next-parser#940]
## To Reproduce

A [minimal reproducible example](https://minimum-reproduction.wtf/).
A [codesandbox](https://codesandbox.io/examples/package/i18next) example or similar
or at least steps to reproduce the behavior:

```js
const key = 'key';
const val = 'val';
t('key', val);
```

## Expected behavior

key will be parsed

```js
{
  "key": "val"
}
```

## Your Environment

- *runtime version*: i.e. node v14, deno, browser xy
- *i18next version*: i.e. 19.5.3
- *os*: Mac, Windows, Linux
- *any other relevant information*

**Comment by karellm** [comment]
It's not a bug. The parser doesn't interpret the code so it cannot do what you ask.
