### ISSUE TITLE
I don't get any output 

### ISSUE THREAD

**Issue by gofreddo** [i18next/i18next-parser#941]
## 🐛 Bug Report

I don't get any output from [i18next-parser](https://github.com/i18next/i18next-parser).  It says  'Stats:  90 files were parsed' but that is it.  No resource files are generated.  

## To Reproduce

i18next --config ./i18next --config i18next-parser.config.mjs --output locales/$LOCALE/$NAMESPACE.json "src/**/*.{ts,tsx}"
Default config file.

## Expected behavior

I expect it to generate resource files.

## Your Environment

- *runtime version*: node v16.19.1
- *i18next version*: 8.9.0
- *os*: Mac

**Comment by katiasmet-93** [comment]
Same issue here.

**Comment by schnogz** [comment]
having same issue.  any ideas as to why?

**Comment by schnogz** [comment]
@gofreddo i realized that i think you need to first manually go through your app and actually wrap some of your strings using `react-i18next`. Once i did that, i got the output as expected

example here:
https://codesandbox.io/p/sandbox/1zxox032q?file=%2Fsrc%2Fapp.js%3A6%2C3-6%2C40

**Comment by karellm** [comment]
Closing by lack of information. Reopen with more detailed information if the issue persists.
