### ISSUE TITLE
Merge old translations

### ISSUE THREAD

**Issue by nickasd** [i18next/i18next-parser#99]
- Is this a bug or a feature request? Feature request
- What version are you running (`0.x` or `1.x`)? 1.0.0-beta14
- Which runner (cli, gulp...)? gulp

1) I think it would be nice if the `translation_old.json` file wasn't replaced each time the parser runs, but instead existing old keys were merged with new old keys. This way the developer could keep running the parser without worrying that old translations get lost and sometime in the future she can go through them and delete the ones are not needed anymore. It happened a couple of times to me that after running the parser once I noticed that some keys didn't get parsed correctly because of typos in my source code and after running it a second time all the old translations were gone.

2) I also think that this file should not be created when there are no old translations, so that when the developers runs the parser and no file is created, she knows that there are no changes to be reviewed.

**Comment by karellm** [comment]
I'm ok with a `removeOldKeys` option that would default to `true`. I'm also ok not creating the old files if empty. Another thing I've meant to implement for a while is to store all the old translations into an array.

If you feel like tackling this, a PR is welcome. My focus is on something else at the moment.

**Comment by nickasd** [comment]
Ok, I will do that.

> Another thing I've meant to implement for a while is to store all the old translations into an array.

What do you mean? Would you rather not preserve the nested json structure?

**Comment by karellm** [comment]
I mean:

```json
{
  "oldKey": [
    "old translation",
    "even older translation"
  ]
}
```

**Comment by nickasd** [comment]
I'm now writing a custom merge function to be used instead of the currently used lodash function `extend` when creating the old catalogue. I have noticed that in `mergeHashes` you are checking if the source and target hashes contain arrays. Can you please explain in what situation this can happen? Because if arrays can really appear in the translation hashes, I would have to structure my update a little bit differently.

**Comment by karellm** [comment]
@nickasd I think this will require a deeper rewrite of the codebase to get this working. First the answer to your question is [here](https://www.i18next.com/translation-function/objects-and-arrays).

I believe that this parser should maintain some sort of a hidden catalog with a specific format. It is currently a limitation for storing all old values, it is also a limitation in implementing #55 

Here is what I've had in mind for a while:

```json
{
  nested: {
    key: {
      paths: [
        'somefile.js'
      ],
      values: [
        "old value",
        "older values"
      ]
    }
  }
}
```

This is a pretty big rewrite though. I might take some time on it this week but no guarantee.
